### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#10]
Add installation instructions, developer guide and usage

**Comment by dtaivpp** [comment]
Hey I just wanted to reach out and see if there were any more plans to create a docs folder similar to the one on the Elasticsearch python client? https://github.com/elastic/elasticsearch-py/tree/v7.15.0/docs
 
I know I used those types of docs several times when I was learning to use the Elasticsearch client. Would it be okay if I started adding that type of documentation here?

**Comment by dblock** [comment]
I think it'd be great if this client exported documentation into https://github.com/opensearch-project/documentation-website _as well as_ make it available in gh-pages through README. Please contribute!

**Comment by PhilipMay** [comment]
@dblock If wanted I can contribute a GH-pages site generated with Sphinx.
Do you want me to?

**Comment by dtaivpp** [comment]
@PhilipMay  I would want you to! haha I was going to ask if we wanted to do that actually as I feel like that is kinda the standard

**Comment by dblock** [comment]
> @dblock If wanted I can contribute a GH-pages site generated with Sphinx. Like this: https://telekom.github.io/HPOflow/code-doc.html Do you want me to?

Please! Don't ask for permission to contribute.

**Comment by PhilipMay** [comment]
> Please! Don't ask for permission to contribute.

The main reason I asked was to avoid duplication of work.

**Comment by PhilipMay** [comment]
Started a PR to generate documentation with Sphinx. See #112

**Comment by stephenleo** [comment]
Is there a way to access the gh-pages doc site?

**Comment by PhilipMay** [comment]
Thanks for bringing this up!
Is is here: https://opensearch-project.github.io/opensearch-py/

A PR to add this to the README.md is still in my list.
