### ISSUE TITLE
Remove cert usage from CI

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-py#103]
* Remove added certs from upstream (https://github.com/opensearch-project/opensearch-py/tree/main/.ci/certs). This will be added as support to security plugin
* Remove references like https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/test.py#L47 
* Remove references from upstream https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/test.py#L40

**Comment by Shivamdhar** [comment]
The pull request has been merged!
