### ISSUE TITLE
Add code coverage section for the library

### ISSUE THREAD

**Issue by Shivamdhar** [opensearch-project/opensearch-py#105]
We should be tracking code coverage for the client library to ensure we are not missing test cases for any new features or a module added in the past. This should be shown as a tag in the README section alongside `CI` and `IntegrationTests` status.

Follow https://app.codecov.io/gh/opensearch-project/opensearch-py/ for setup and further instructions.
Example repo for reference: https://github.com/codecov/example-python

**Comment by anasalkouz** [comment]
Anyone tracking this? is there a reason why we keep this issue untriaged for longtime?

**Comment by dblock** [comment]
Yes, this should be a child of https://github.com/opensearch-project/opensearch-clients/issues/30, we still need code coverage. cc: @wbeckler

**Comment by bl1nkker** [comment]
Hello! 

I looked through the rest of the repositories and realized that opensearch-py is one of the repositories where codecov is not integrated. For this reason, it is not possible to visualize test coverage. 

I can solve this problem. Before that, I had to work with codecov integration on my personal projects. The only question is: is this problem still relevant?

**Comment by bl1nkker** [comment]
If the issue itself is already outdated, then I will open a new one, since test coverage is really necessary for this project
