### ISSUE TITLE
How to migrate from ElasticSearch to OpenSearch?

### ISSUE THREAD

**Issue by laysauchoa** [opensearch-project/opensearch-py#109]
First of all, thanks for the amazing library. 
I have more knowledge on ElasticSearch and I am learning more about OpenSearch now. 
I have a question and please, do let me know if this is the right place to ask.

**Question:**
1) Where in the code should I find more information about it. Would be possible to point it out?

**Comment by dtaivpp** [comment]
@laysauchoa  Now I see why you reached out to me on twitter! Most, if not all of your knowledge about Elasticsearch should be directly transferable to OpenSearch. Most of our repo's are a direct fork of several of theirs from when they were open source. 

As for how to migrate from Elasticsearch to OpenSearch do you mean how to move your data from one cluster to another or how to migrate from their client to this one?

**Comment by wbeckler** [comment]
Unless there are any objections I will close this issue as solved.
