### ISSUE TITLE
Missing SecurityClient - Inability to configure roles, role mappings and users

### ISSUE THREAD

**Issue by andyfase** [opensearch-project/opensearch-py#110]
Seemingly the [ElasticSearch security client](https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/_sync/client/security.py) was deleted as part of a commit removing [xpack features ](https://github.com/opensearch-project/opensearch-py/commit/a41fd13d2d8a9bc8d800a53faedeb8e11d4cccd0). Though their maybe be xpack features in this client, it also contains methods that are needed to configure the following on AWS OpenSearch. Namely

- role methods (get, put, delete)
- user methods (get, put, delete)
- mapping methods  (get, put, delete)

Is there a plan to add this library back even in a reduced form? otherwise developers will be forced to revert. back to the elasticsearch-py lib for this kind of functionality.

Thanks

**Comment by andyfase** [comment]
Note. I appreciate that I was wrong above, and the Security Client is the Native ES one and does not the OpenDistro ES client API endpoiints. 

Still the question remains if this library intends to release or would be interested in supporting core opendistro based methods for the types of methods mentioned above. Thanks.

**Comment by anitakrueger** [comment]
I'd be interested in this as well, because it seems I cannot use the native Elasticsearch client on my OpenSearch cluster.
`elasticsearch7.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch`
(using `elasticsearch7` python client on a `7.10.2` OpenDistro Elasticsearch.)

**Comment by anitakrueger** [comment]
I got the native Elasticsearch client to work, but of course the SecurityClient doesn't work because of the difference in API endpoints.
How do I programmatically manage users and roles without making direct HTTP calls?

**Comment by dblock** [comment]
This is similar to https://github.com/opensearch-project/opensearch-py/pull/93. That PR is in a good shape and just needs to be finished. Similarly we would need to add security plugin endpoints  here. Maybe someone wants to pick this up?
