### ISSUE TITLE
[FEATURE] Respect SSL certificate environment variables

### ISSUE THREAD

**Issue by aiudirog** [opensearch-project/opensearch-py#111]
**Is your feature request related to a problem?**
I can't configure SSL cert files with the urllib3 backend through environment variables because certifi is chosen by default here: https://github.com/opensearch-project/opensearch-py/blob/cfe1190a2297226468e86dcf697d8b07b6020df5/opensearchpy/connection/http_urllib3.py#L56

This is preventing me from configuring a company SSL certificate on the fly when deploying to Lambda which isn't required in other deployments.

**What solution would you like?**
Check SSL_CERT_FILE/SSL_CERT_DIR environment variables before defaulting to certifi's CA bundle.

**What alternatives have you considered?**
You can configure it manually in code, but this makes portable deployments more challenging.

**Do you have any additional context?**
N/A

**Comment by wbeckler** [comment]
@aiudirog  Feel free to create a PR for this.
