### ISSUE TITLE
[FEATURE] High Level API

### ISSUE THREAD

**Issue by PhilipMay** [opensearch-project/opensearch-py#113]
This is a mix of question and feature request:

Do you plan to develop a high level Python API? Where do you plan to develop it?
Here or as an extra project?

Specifically, I'm interested in a batch API, for example. And I could provide PRs.

Can we reuse the elastic helper functions? See here: https://github.com/elastic/elasticsearch-py/tree/a5b38828740381148fd0642863a579be17d36eaa/elasticsearch/helpers

**Comment by VachaShah** [comment]
@PhilipMay Any chance this is covered in the High Level Python Client https://github.com/opensearch-project/opensearch-dsl-py?

**Comment by PhilipMay** [comment]
> @PhilipMay Any chance this is covered in the High Level Python Client https://github.com/opensearch-project/opensearch-dsl-py?

Not sure. Sorry.

**Comment by wbeckler** [comment]
@PhilipMay feel free to contribute PRs to improve the APIs. There is a high-level, albeit poorly documented, version of the python client, as mentioned above, but there's no reason to hold back from improving the interface of the main client.

In terms of the above-mentioned helper functions, as long as you abide by licensing and IP rules, you can reuse code.

**Comment by dblock** [comment]
Closing because we do have a high level API and a beginning of documentation for it in https://github.com/opensearch-project/opensearch-py/blob/main/guides/dsl.md.
