### ISSUE TITLE
Update README regarding opensearch-dsl

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-py#117]
We successfully released opensearch-dsl. Update the welcome section to reflect the same (https://github.com/opensearch-project/opensearch-py/blob/main/README.md#welcome)

**Comment by VachaShah** [comment]
Being addressed in PR https://github.com/opensearch-project/opensearch-py/pull/178

**Comment by wbeckler** [comment]
It looks like https://github.com/opensearch-project/opensearch-py/pull/178  has been deleted and therefore this still needs doing.

**Comment by VachaShah** [comment]
opensearch-dsl-py is merged into opensearch-py as part of #194. Tracking this issue to remove any references to the high-level/low-level client terminology.
