### ISSUE TITLE
Bug: black does not support Python 2 anymore - need to fix the linter

### ISSUE THREAD

**Issue by PhilipMay** [opensearch-project/opensearch-py#119]
see https://github.com/opensearch-project/opensearch-py/runs/5028094085?check_suite_focus=true#step:5:15

I can provide a PR. Should we move to py33 or other Version?
Or shold we version pin black to an old version?

**Comment by dtaivpp** [comment]
I feel like we should move to py33 support. The current release of black is the first one that is no longer beta and I think it's valuable to stay on the non-beta release. In addition python 2 was officially deprecated Jan 1 of this year.

**Comment by PhilipMay** [comment]
fix is done in PR #120

**Comment by PhilipMay** [comment]
fixed in #120 - closing
