### ISSUE TITLE
[BUG] OpenSearch.index() erroneously invokes PUT method resulting in data loss 

### ISSUE THREAD

**Issue by sepiariver** [opensearch-project/opensearch-py#132]
**What is the bug?**
At https://github.com/opensearch-project/opensearch-py/blob/65c12d7224c9b57d60397f1069e4cbaa1caea6d6/opensearchpy/client/__init__.py#L358

We do: `"POST" if id in SKIP_IN_PATH else "PUT"`

Logically this means "If no id, POST" therefore "If id, PUT"

According to the API reference here: https://opensearch.org/docs/latest/opensearch/index-data/

> POST requests make partial updates to documents. To altogether replace a document, use a PUT request

If id is provided, and the user intends to update a document, but PUT is used, the document will be overwritten. The expression should be the inverse. Anecdotally we observed this in our implementation.

**How can one reproduce the bug?**

1. Index a document

```
# instantiate OpenSearch as client
# index a document
client.index(
    index=movies,
    id=1234,
    body={
      'doc': {
        'title': "Castle in the Sky",
        'genre': ["Animation", "Fantasy"]
      }
    }
)
```

2. Update the document

```
# update document
client.index(
    index=movies,
    id=1234,
    body={
      'doc': {
        'genre': ["Animation", "Fantasy"]
      }
    }
)
# the document lacks the title property, having been overwritten
```

**What is the expected behavior?**

When an id is provided, the POST method is used to update a document in accordance with the API reference. A partial update does not overwrite the entire document.

**What is your host/environment?**
 - OS: macOS 
 - Version 10.15.7 (19H1615)
 - Plugins

**Do you have any screenshots?**
not applicable

**Do you have any additional context?**

In actuality the REST API does not seem to conform to the behavior described in the documentation. Whether POST or PUT is used, the document is overwritten. That is perhaps why this bug hasn't been raised before: people just use the `OpenSearch.update()` method. One solution might be to fix the documentation and maybe remove the erroneous line, because in effect it does nothing. To bring everything in line with the expected and currently documented behavior, both the API and this client (and other clients?) need to be fixed.

**Comment by wbeckler** [comment]
First, this looks like a big gap in the core docs for OpenSearch. Second, the python client is using the wrong verb, and if it doesn't matter, then the conditional should be removed. Third, this sounds like a bug in the OpenSearch server in handling POST without `/update`. 

Am I getting this right? Feel free if anyone wants to propose new issues in core or docs.

**Comment by saimedhi** [comment]
@sepiariver please use "update" if you would like to make certain changes for an existing document without over writing the document. And use "index" if you would like to overwrite a document.
