### ISSUE TITLE
[Upgrade]: Remove type mapping support 

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-py#134]
**Is your feature request related to a problem?**
As part of v2.0 release, mapping type are removed from OpenSearch engine. Need to remove the support of type from clients
Issue [1940](https://github.com/opensearch-project/opensearch/issues/1940)

**What solution would you like?**
Upgrade the client code to remove usage of 
- Type API end-points
- Remove include_type_name parameter from requests.

**What alternatives have you considered?**

**Comment by VijayanB** [comment]
@dreamer-89 Shall we move this issue to https://github.com/opensearch-project/opensearch-clients , since this is applicable for all of the clients. What do you think?

**Comment by dreamer-89** [comment]
@VijayanB : This sounds correct. Thanks for pointing out.
