### ISSUE TITLE
[BUG] helpers.bulk action is incorrectly typed

### ISSUE THREAD

**Issue by pejter** [opensearch-project/opensearch-py#154]
**Is your feature request related to a problem?**
When using helpers.bulk in a typed environment I need to manually cast the result to either tuple[int, int] or tuple[int, list[Any]] depending on the value of stats_only argument.

**What solution would you like?**
You can introduce overloads to the relevant functions which return different types depending on arguments like `helpers.bulk`
```python
@overload
def bulk(
    client: OpenSearch,
    actions: Iterable[Any],
    stats_only: Literal[True] = ...,
    ignore_status: Optional[Union[int, Collection[int]]] = ...,
    *args: Any,
    **kwargs: Any
) -> Tuple[int, int]: ...

@overload
def bulk(
    client: OpenSearch,
    actions: Iterable[Any],
    stats_only: Literal[False],
    ignore_status: Optional[Union[int, Collection[int]]] = ...,
    *args: Any,
    **kwargs: Any
) -> Tuple[int, List[Any]]: ...
```

**Comment by wbeckler** [comment]
Can you imagine a scenario where introducing this fix would break someone's already working code that relied on the old result typing? If so we'd need to keep track of which version we do this in, or maybe fix it in a way that couldn't break old code.

**Comment by pejter** [comment]
I don't think there's a way you can depend on this that breaks with the proposed change.
The overall function type stays the same, so if you passed an arbitrary bool to the function then you'd get the same resulting type.
But if you passed True or False you'd now get a more specific type instead of the generic one.

In the end adding overloads doesn't change anything when it comes to the existing code, the original function definition is still the same (just with an added @overload decorator) and it behaves exactly the same, but there is now additional information for the typing system in the form of the other 2 overloads which I've posted. If you imagine a diff for this change it would just be adding the above lines plus the @overload decorator for the actual implementation.

**Comment by wbeckler** [comment]
This makes total sense. Feel free to submit a PR for this.

**Comment by wbeckler** [comment]
@pejter Would you be up for submitting a PR for this?

**Comment by harshavamsi** [comment]
@saimedhi can you take a look?

**Comment by saimedhi** [comment]
yes
