### ISSUE TITLE
[BUG] unexpected keyword error when switching to opensearch

### ISSUE THREAD

**Issue by cbarton4** [opensearch-project/opensearch-py#157]
I'm switching over a fastapi application from elasticsearch to opensearch, and a number of unit tests fail, near as I can tell, all GET  requests to the '/search' endpoint produce an error of this type:

ERROR api/test_api.py::test_app_search_response - TypeError: search() got an unexpected keyword argument 'query'

Code in question:
```
def test_app_search_response(load_test_data, app_client, es_transactions):
    item = load_test_data("test_item.json")
    os_transactions.create_item(item, request=MockStarletteRequest)

    resp = app_client.get("/search", params={"ids": ["test-item"]})
    assert resp.status_code == 200
    resp_json = resp.json()

    assert resp_json.get("type") == "FeatureCollection"
    # stac_version and stac_extensions were removed in v1.0.0-beta.3
    assert resp_json.get("stac_version") is None
    assert resp_json.get("stac_extensions") is None

    es_transactions.delete_item(
        item["id"], item["collection"], request=MockStarletteRequest
    )
```

There's no 'query' keyword at play here, and none in any of the references.  I was expecting opensearch-py to be a 1-1 replacement of the elasticsearch equivalent (this test succeeded as written before swapping to OS from ES), but either I'm using it incorrectly here (entirely possible) or there's a bug in the connector that is preventing this from executing as it would for the other.

I'm testing in Docker on MacOS, opensearch-py and opensearch-dsl are both at 1.0.0, opensearch 1.2.4, latest alpine.

Further context if helpful:
App in question is stac_fastapi_elasticsearch (https://github.com/stac-utils/stac-fastapi-elasticsearch).  Opensearch port is TBD on feature vs fork, and not yet public.

**Comment by cbarton4** [comment]
https://github.com/stac-utils/stac-fastapi-elasticsearch/blob/main/stac_fastapi/elasticsearch/tests/api/test_api.py line 67 and following.  I've basically got a copy of this app where I'm trying to swap 1-for-1 elasticsearch-py for opensearch-py, and I see this error with multiple unit tests.  Honestly just trying to determine if its a usage error on my part or if it's a genuine bug in the connector, but I was asked to open a ticket here.

**Comment by dblock** [comment]
@cbarton4 were you able to resolve it? presumably there should be no changes between ES 7.10 and OpenSearch 1.0. But I am not familiar with your application, as @Jon-AtAWS pointed out, look like this request is not made against OpenSearch. If you have a simple way to reproduce your problem for us (a fork with your changes and a 1-liner to run tests?) maybe someone can take a look?

**Comment by cbarton4** [comment]
This appears to come from a change in the API with the release of the client subsequent to the OpenSearch fork, I've managed to resolve it locally and will close the issue.
