### ISSUE TITLE
request [/condidates/_doc/_search] contains unrecognized parameters: [scroll], [size][BUG]

### ISSUE THREAD

**Issue by ynang** [opensearch-project/opensearch-py#164]
After I  update image for opensearchproject/opensearch:latest and opensearchproject/opensearch-dashboards:latest in my docker container,the error occurs when I use scan API of python elasticsearch helpers client:

`HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'request [/condidates/_doc/_search] contains unrecognized parameters: [scroll], [size]')`
The request demo like this:

```python
from opensearchpy import helpers
helpers.scan(opensearch_client,
                                            index="condidates",
                                            query={
                                                "query": {
                                                    "bool": {"must": [
                                                        {"term": {
                                                            "search_key.owner.age": {
                                                                "value": 22
                                                            }
                                                        }}
                                                    ]}
                                                }
                                            },
                                            doc_type="_doc"
                                            )
```

but the scan's definition as fllows:

```python
def scan(
    client,
    query=None,
    scroll="5m",
    raise_on_error=True,
    preserve_order=False,
    size=1000,
    request_timeout=None,
    clear_scroll=True,
    scroll_kwargs=None,
    **kwargs
)
```
maybe python client need to be updated~~

**Comment by wbeckler** [comment]
@ynang is this still happening?

**Comment by harshavamsi** [comment]
@saimedhi can you take a look at this?

**Comment by saimedhi** [comment]
@ynang could you please check if you are still getting error. I replicated your request using OpenSearch version 1.3.2 and opensearch-py version 1.1.0 and didn't get any error.
