### ISSUE TITLE
API Reference - python docs please!

### ISSUE THREAD

**Issue by jtlz2** [opensearch-project/opensearch-py#171]
**Is your feature request related to a problem?**

I am always frustrated because in spite of sample documentation online there is an absence of a python API reference and/or easy-to-find docstrings. I have to go digging into the code to figure out function signatures. It would really speed up development if you would be able to post this somewhere.

**What solution would you like?**
An online API reference on e.g. readthedocs.io

**What alternatives have you considered?**
Sample code on SO or on github, plus digging into the code (time consuming and difficult to interpret!).

**Do you have any additional context?**
Please advise if I am missing where this is. If it's there, please simply make it easier to find!

Many thanks!

**Comment by VachaShah** [comment]
Hi @jtlz2, @PhilipMay recently added the Sphinx link https://opensearch-project.github.io/opensearch-py/. Hope that helps!

**Comment by jtlz2** [comment]
@VachaShah @PhilipMay Thank you - that is 💯 what I needed! Please could you make it more prominent around the place? If you hadn't told me I don't think I'd have found it. Thanks again!

**Comment by PhilipMay** [comment]
> Please could you make it more prominent around the place?

@jtlz2 what exactly do you mean? Maybe you want to provide a PR?

**Comment by jspreddy** [comment]
I am still having to dig through the code base to figure things out. The [python API documentation here ](https://opensearch-project.github.io/opensearch-py/api-ref.html#api-reference) is not complete. It only contains docs for top level classes. 

> The instance has attributes cat, cluster, indices, ingest, nodes, snapshot and tasks that provide access to instances of CatClient, ClusterClient, IndicesClient, IngestClient, NodesClient, SnapshotClient and TasksClient respectively. This is the preferred (and only supported) way to get access to those classes and their methods.

None of these classes are available in the reference.

**Comment by harshavamsi** [comment]
@jspreddy the docs need improvement. Would you be willing to contribute a PR for the ones you see lacking?

**Comment by jaydm26** [comment]
@harshavamsi Happy to take this up, if no one has volunteered yet

**Comment by harshavamsi** [comment]
Hi @jaydm26, absolutely go for it. Thanks!

**Comment by jaydm26** [comment]
Hey @harshavamsi, I have raised a PR #204

**Comment by VachaShah** [comment]
Closing this issue since docs have been added.
