### ISSUE TITLE
[BUG] Connection Leak

### ISSUE THREAD

**Issue by venugopalnaiduch** [opensearch-project/opensearch-py#172]
There seams to be a connection leak issue when connections are left idle. Ideally if any connection that cannot be used must be closed.

Sample Code:-

import asyncio
import ssl
from opensearchpy import AsyncOpenSearch
from opensearchpy.connection import create_ssl_context
ssl_context = create_ssl_context()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE

async def run():
    client = AsyncOpenSearch("<URL>", http_auth=("<username>", "<password>"),
                                                verify_certs=False, ssl_context=ssl_context, maxsize=1,
                                                ssl_show_warn=False,
                                                headers={"securitytenant": "<tenant>"})
    count = 0
    while True:
        data = await client.get("<Index>", "myid")
        count += 1
        if count == 100:
            await asyncio.sleep(30)
            count = 0            
            
if __name__ == "__main__":
    asyncio.run(run())

When we look at the lsof output after every 30 seconds
**lsof | grep 9200 | wc -l**
30seconds:- 16 
60 seconds:- 32
90 seconds:- 48 ..

If i remove the sleep the connection count does not increase.
Any help will be appreciated
Thanks In Advance,
venugopalnaidu Ch.

**Comment by wbeckler** [comment]
This is a good catch. When this is fixed it would be great to add a test for this.

**Comment by wbeckler** [comment]
@venugopalnaiduch would you be up for taking a stab at a PR for this?

**Comment by wbeckler** [comment]
@saimedhi can you take a look?

**Comment by saimedhi** [comment]
I will work on it.

**Comment by saimedhi** [comment]
> @saimedhi hi! How're are you going with the issue? Do you need help?

Hello Reffy, Sorry for not getting started on this issue sooner. It's on my to-do list. It would be fantastic if you could work on this issue.

**Comment by Refffy** [comment]
I'll work on this issue

**Comment by saimedhi** [comment]
Hello @Refffy, I'd like to know whether you were able to reproduce this bug?

**Comment by saimedhi** [comment]
Hello @venugopalnaiduch, please refer to this example [code](https://github.com/dblock/opensearch-python-client-demo/blob/main/async/example.py). It might help in this scenario. As far as I understood, we can close the client session at the end of execution as given in the example.

**Comment by venugopalnaiduch** [comment]
Hi @saimedhi,

Thanks for sharing the sample code, we will try and let you know.

**Comment by Refffy** [comment]
@ArkTZ ok, no problem! Feel free to PR and ask any questions

**Comment by saimedhi** [comment]
@Refffy, @ArkTZ  Please feel free to take up this issue and raise a PR with your proposed solution. Thanks :)
