### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tyagian** [opensearch-project/opensearch-py#173]
**What is the bug?**

The documentation here https://opensearch.org/docs/latest/opensearch/index-data/
mentions if data formatted with index name, it should use index name from data itself. 

logs = `[
{ "index": { "_index": "index-2022-06-08", "_id": "<id>" } }
{ "A JSON": "document" } \n
{ "index": { "_index": "index-2022-06-09", "_id": "<id>" } }
{ "A JSON": "document" } \n
{ "index": { "_index": "index-2022-06-10", "_id": "<id>" } }
{ "A JSON": "document" }
]`

but I am using opensearch-py helpers bulk api to do the same. Although I have to mention index name as a parameter in the bulk api request. 

Here is the snippet of request
```
client = OpenSearch(
            hosts = [{'host': host, 'port': 443}],
            http_auth = awsauth,
            use_ssl = True,
            verify_certs = True,
            connection_class = RequestsHttpConnection
            )
        
        resp = helpers.bulk(client, logs, index= index_name, max_retries = 3)

```
If I don't mentioned index name parameter, I get 4xx error, indices missing. I can't find any example to replicate this. I also asked same question in the community. 
https://forum.opensearch.org/t/bulk-operation-using-python/9887

Also, I checked in the source code, 
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/actions.py#L373
It doesn't look like index_name is required. 

Any help would be appreciated.

**Comment by harshavamsi** [comment]
Hi @tyagian,

Looks like you're using the helper library instead of the actual client. You're right that you do not need to specify the `index` when you call the `bulk` API.

Here's what the input looks like: 

```
logs = '{"index": {"_index": "index-2022-06-08", "_id": "<id>"}} \n 
{"name": "foo"} \n 
{"index": {"_index": "index-2022-06-09", "_id": "<id>"}} \n 
{"A JSON": "document"} \n 
{"index": {"_index": "index-2022-06-10", "_id": "<id>"}} \n 
{"A JSON": "document"}'
```

Snippet that bulk indexes:

```python
client.bulk(logs)

# Search for the document.
q = 'doc'
query = {
    'size': 5,
    'query': {
        'multi_match': {
            'query': q,
            'fields': ['name']
        }
    }
}

response = client.get(
    index="index-2022-06-08",
    id="<id>"
)
print('Get result:')
print(response)
```

And the response:
```
Get result:
{'_index': 'index-2022-06-08', '_id': '<id>', '_version': 8, '_seq_no': 7, '_primary_term': 1, 'found': True, '_source': {'name': 'foo'}}
```

**Comment by harshavamsi** [comment]
@tyagian adding on to that, here's an example of how to do it with the helper functions.

```python
keys = []
def generate_data():
    mywords = ['foo', 'bar', 'baz']
    for index, word in enumerate(mywords):
        keys.append({
            "_index": "mywords",
            "word": word,
            "_id": index
        })
    return keys

helpers.bulk(client, generate_data(), max_retries=3)
```

The bulk helper function accepts an `action` iterable or a generator(preferred while loading large data that has memory constraints).

**Comment by wbeckler** [comment]
Hi @tyagian 
Does this help?

@harshavamsi are there any places we can put these examples in the docs, if they aren't there already?

**Comment by wbeckler** [comment]
closing, as the docs have been updated.
