### ISSUE TITLE
[FEATURE] Add support for inclusive naming

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-py#174]
Add support for inclusive naming by deprecating the master nomenclature.

See meta issue https://github.com/opensearch-project/opensearch-clients/issues/16 for details.

**Comment by amoghtewari** [comment]
@VachaShah I was able to list all files that have one or more occurrences of the string "master" (with the context mentioned in the meta issue). May I ask to be assigned this issue? I'll open a PR and make changes.

https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/__init__.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/__init__.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cat.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cat.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cluster.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cluster.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/dangling_indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/dangling_indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/features.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/features.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/ingest.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/ingest.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/snapshot.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/snapshot.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/__init__.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/__init__.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cat.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cat.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cluster.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cluster.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/dangling_indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/dangling_indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/features.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/features.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/ingest.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/ingest.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/transport.py

**Comment by amoghtewari** [comment]
@VachaShah, I was able to list all files that have one or more occurrences of the string "master" (with the context mentioned in the meta issue). May I ask to be assigned this issue? I'll open a PR and make changes.

https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/__init__.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/__init__.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cat.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cat.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cluster.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/cluster.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/dangling_indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/dangling_indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/features.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/features.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/ingest.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/ingest.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/snapshot.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/client/snapshot.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/__init__.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/__init__.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cat.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cat.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cluster.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/cluster.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/dangling_indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/dangling_indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/features.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/features.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/indices.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/indices.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/ingest.py
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/ingest.pyi
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/transport.py
https://github.com/opensearch-project/opensearch-py/blob/main/test_opensearchpy/test_async/test_transport.py
https://github.com/opensearch-project/opensearch-py/blob/main/test_opensearchpy/test_transport.py

**Comment by VachaShah** [comment]
Thank you @amoghtewari! Assigning you

**Comment by amoghtewari** [comment]
Hi @VachaShah , I was attempting to run the nox test suite and got the following error (limiting myself to Python 3.9 for now)

![window](https://user-images.githubusercontent.com/20358518/184198044-f50e2cdf-6c46-471c-9763-86ca151ba23d.png)
 
Have you or anyone else encountered a similar message? Am I missing something obvious?

**Comment by VachaShah** [comment]
Hi @amoghtewari, can you paste your repo link with the code changes and I can take a look? I have not seen this error for the nox command as of yet but would be helpful to look at the changes.

**Comment by amoghtewari** [comment]
Hi @VachaShah, here's my fork, https://github.com/amoghtewari/opensearch-py which I was able to test alongside the docker image with nox ( apparently the bugs were from not having set up the SSL certs so I disabled security since it has no intersection with my changes, was able to pass 65% of the tests, the failed ones required ssl), Please take a look and let me know if this works as expected.

**Comment by harshavamsi** [comment]
@amoghtewari can you raise a PR? It is easier to measure changes that way. Thanks.

**Comment by wbeckler** [comment]
Hi @amoghtewari, are you planning on PR'ing this? Is there anything others could do to help you put it together for a PR?

**Comment by amoghtewari** [comment]
Hi @harshavamsi & @wbeckler , My apologies for the delay.
Here's the PR, please let me know what you think.
https://github.com/opensearch-project/opensearch-py/pull/212/

**Comment by wbeckler** [comment]
Hi @amoghtewari, did you see the comments on your PR about the DCO?

**Comment by amoghtewari** [comment]
Yes. I'm swamped at work in the foreseeable future, so I request you to re-assign this issue.

**Comment by harshavamsi** [comment]
@amoghtewari @wbeckler I can create a PR on the fork to make the rest of the changes.
