### ISSUE TITLE
[FEATURE] Testing compatibility on different platforms

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-py#186]
### Is your feature request related to a problem?
We test our clients for Linux platform but we do not know if these clients work smoothly on platforms like windows/mac etc.
Coming from https://github.com/opensearch-project/opensearch-clients/issues/18

### What solution would you like?
Test the client with most popular platforms and CPU architectures:

- x64
- ARM
- Linux
- Windows
- MacOS

**Comment by dblock** [comment]
With #569 we have all the ones that are supported by GHA, closing.
