### ISSUE TITLE
[FEATURE] Standardize, setup, report, and increase test coverage

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-py#197]
Setup code coverage, once reporting from CI/CD analyze the test gap and fill it.

See the meta issue https://github.com/opensearch-project/opensearch-clients/issues/30 for details.

**Comment by wbeckler** [comment]
Related: https://github.com/opensearch-project/opensearch-py/issues/105

**Comment by bl1nkker** [comment]
Should we close this issue?

resolved at #315
