### ISSUE TITLE
[FEATURE] Add license header check for new files

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-py#200]
### Is your feature request related to a problem?
Incoming new files must be checked for [OpenSearch licenses](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#license-headers)

### What solution would you like?
A similar approach to https://github.com/opensearch-project/opensearch-net/blob/main/.github/check-license-headers.sh

**Comment by margulanz** [comment]
Is this issue still relevant?
