### ISSUE TITLE
[BUG] Remove outdated maintainer(s)

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#202]
### What is the bug?
I'm out of Amazon, and for the sake of clarity, would like to be removed from maintainers list of the repo. We can check for other people too and update the list to reflect current maintainers. 

### How can one reproduce the bug?
Check MAINTAINERS.md 

### What is the expected behavior?
Should reflect current maintainers.

### What is your host/environment?
N/A

### Do you have any screenshots?
N/A

### Do you have any additional context?
No

**Comment by dblock** [comment]
@rushiagr You don't have to lose your maintainer privileges but you can if you want to, make a PR to get removed and we'll check permissions as well? 

@wbeckler is synching up maintainers I believe across client repos

**Comment by harshavamsi** [comment]
Addressed in https://github.com/opensearch-project/opensearch-py/pull/219. Closing.
