### ISSUE TITLE
[PROPOSAL] Custom connection pooling option for `connection_class=RequestsHttpConnection`.

### ISSUE THREAD

**Issue by Neckbuster** [opensearch-project/opensearch-py#203]
## What/Why

- Custom Connection pooling option for ` connection_class=RequestsHttpConnection`.
- This feature is required because clients who are using advanced auth plugins options like AWS_IAM are forced to used RequestHttpConnection and are stuck with default values i.e 10 pool max_size provided in request library.

### What are you proposing?
 A new connection_class that will be a child class of  `RequestsHttpConnection` with custom connection_pool option like pool_max_size that will be provided from client. The `session` attribute in `RequestHttpConnection` will be mounted with requests adapters with these pooling options.

**Comment by harshavamsi** [comment]
@Neckbuster I think this is a good idea. I see that the default connection class has the `maxsize` attribute. Would be nice to replicate that in the `RequestHttpConnection` class. Out of curiosity could you  lay out your implementation idea here? To me it looks like you would not only need to update the pooling options in the session but also make use of `self.pool.urlopen` to allow for the actual pooling to take place?

**Comment by harshavamsi** [comment]
Closing via #216
