### ISSUE TITLE
[FEATURE] Rename GETTIING_STARTED to USER_GUIDE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#227]
### Is your feature request related to a problem?

- GETTING_STARTED is a lot more than a getting started
- We want to ensure all new features are documented
- Other projects have USER_GUIDE.md, seems like it's becoming a convention ([example](https://github.com/opensearch-project/opensearch-rs/blob/main/USER_GUIDE.md))

### What solution would you like?

- Rename https://github.com/opensearch-project/opensearch-py/blob/main/GETTING_STARTED.md to USER_GUIDE.
- Do an editing pass on the guide to fix any small stuff.
- Make sure to link it from README.

**Comment by saimedhi** [comment]
I am working on this
