### ISSUE TITLE
[BUG] Indexed document using opensearch-py cannot be found by search

### ISSUE THREAD

**Issue by leontp587** [opensearch-project/opensearch-py#255]
### What is the bug?
I used opensearch-py library to create an index, add a document to the index, and then search for the document. Unexpectedly, the document was not found by an exact match search, even though I confirmed that the document existed in the index.

### How can one reproduce the bug?
The following code was used to connect to a OpenSearch cluster to create an index, add a document to the index, and then search for the document:

```
from opensearchpy import OpenSearch
import uuid

user="admin
password="REMOVED_FOR_SECURITY"

# connect to OpenSearch using python opensearch client
client = OpenSearch(
    hosts = [{"host": "OPENSEARCH_HOSTNAME", "port": 443}],
    http_auth = (user, password),
    use_ssl = True
)

# Create the index named "people"
index_name = 'people'
index_body = {
  'settings': {
    'index': {
      'number_of_shards': 1,
      "number_of_replicas": 0
    }
  }
}

response = client.indices.create(index_name, body=index_body)
print('\nCreating index:')
print(response)

# index one record
index_one_record = {
    "data1:": "uytsasdfg"
}

print('\nIndex one record:')
print(client.index(
    index = "people",
    body=index_one_record,
    id=uuid.uuid4(),
    refresh=True
))

# search for this record
print('\nSearch for this record:')
res = client.search(index="people", body = {
    "query": {
        "match": {
            "data1": "uytsasdfg"
        }
    }
})

print(res)
```

### What is the expected behavior?
Since refresh=True for client.index(), I expected the document to be immediately available for search. However, the client.search() command above produced no results:
`{'took': 1, 'timed_out': False, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}, 'hits': {'total': {'value': 0, 'relation': 'eq'}, 'max_score': None, 'hits': []}}`

Furthermore, after running the above code, I went to OpenSearch's DevTools, and tried to search for the record with the API call:
```
GET /people/_search
{
    "query": {
        "match": {
            "data1": "uytsasdfg"
        }
    }
}
```
This API call also found no records.
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

To make sure the record actually existed, I called "GET /people/_search" without any body, and there was able to find the document is indeed there.
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "people",
        "_id" : "6486e56d-b48f-44d4-88d2-7ee9199ce6b0",
        "_score" : 1.0,
        "_source" : {
          "data1:" : "uytsasdfg"
        }
      }
    ]
  }
}

```

Overall, the result shows that using opensearch-py to create an index, then add a document as the code performs results in the document not being findable on search, even though the document is confirmed to exist in the index.

### What is your host/environment?
OpenSearch version used:
OpenSearch 2.3 (latest)
R20221114-P1 (latest)

My python version is: 3.9.6
The "opensearch-py" library version I used is: 2.0.1

### Do you have any screenshots?
No screenshots

### Do you have any additional context?
No other context

**Comment by harshavamsi** [comment]
Hi @leontp587, there is a typo in your search. 

You are indexing:

 ```{
    "data1:": "uytsasdfg"
}```

But searching for 

```
{
        "match": {
            "data1": "uytsasdfg"
        }
    }
```

There's an extra `:`
