### ISSUE TITLE
[BUG] Timeout parameter doesn't work when calling client.indices.delete()

### ISSUE THREAD

**Issue by mle-els** [opensearch-project/opensearch-py#260]
### What is the bug?
Timeout parameter doesn't work when calling `client.indices.delete()`

### How can one reproduce the bug?

Set up a new environment:

```bash
conda create -p ./.conda
conda install pip
pip install opensearch-py
```

Create and run a Python file with the following content:

```python
from opensearchpy import OpenSearch

host = 'localhost'
port = 9200
auth = ('admin', 'admin')

client = OpenSearch(
    hosts = [{'host': host, 'port': port}],
    http_auth = auth,
    use_ssl = True,
    verify_certs=False, ssl_show_warn = False,
)

client.indices.delete(
    index = 'no-such-index', ignore_unavailable=True, timeout=120
)
```

This is the output that I got:

```
(/Users/le3/Downloads/test-opensearch-py/.conda) le3@ELSAMSM-400611 test-opensearch-py % python test.py
Traceback (most recent call last):
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/util/timeout.py", line 150, in _validate_timeout
    if value <= 0:
       ^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/connection/http_urllib3.py", line 240, in perform_request
    response = self.pool.urlopen(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 691, in urlopen
    timeout_obj = self._get_timeout(timeout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 334, in _get_timeout
    return Timeout.from_float(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/util/timeout.py", line 179, in from_float
    return Timeout(read=timeout, connect=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/util/timeout.py", line 103, in __init__
    self._connect = self._validate_timeout(connect, "connect")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/urllib3/util/timeout.py", line 158, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was 120, but it must be an int, float or None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/le3/Downloads/test-opensearch-py/test.py", line 14, in <module>
    client.indices.delete(
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/client/utils.py", line 178, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/client/indices.py", line 304, in delete
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/transport.py", line 406, in perform_request
    raise e
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/transport.py", line 369, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/le3/Downloads/test-opensearch-py/.conda/lib/python3.11/site-packages/opensearchpy/connection/http_urllib3.py", line 255, in perform_request
    raise ConnectionError("N/A", str(e), e)
opensearchpy.exceptions.ConnectionError: ConnectionError(Timeout value connect was 120, but it must be an int, float or None.) caused by: ValueError(Timeout value connect was 120, but it must be an int, float or None.)
```

### What is the expected behavior?
The method should run without error.

### What is your host/environment?
Mac OSX 12.4

**Comment by harshavamsi** [comment]
@saimedhi Can you take a look?

**Comment by mle-els** [comment]
Added observed output to the desc.

**Comment by mle-els** [comment]
One way to solve this error is to change `opensearchpy/client/utils.py:query_params:_wrapper` to avoid `_escape()` the `timeout` param.

**Comment by saimedhi** [comment]
> @saimedhi Can you take a look?

I will work on it.

**Comment by saimedhi** [comment]
@mle-els Please take a look at the [documentation](https://github.com/saimedhi/opensearch-py/blob/054d6691394b7dd897f0e4ea54aee2a8c886815e/opensearchpy/transport.py#L356). params is a dictionary of query parameters. So, the following implementation will work. 

client.indices.delete(
    index = index_name, params={"timeout":120}
)

**Comment by mle-els** [comment]
> @mle-els Please take a look at the [documentation](https://github.com/saimedhi/opensearch-py/blob/054d6691394b7dd897f0e4ea54aee2a8c886815e/opensearchpy/transport.py#L356). params is a dictionary of query parameters. So, the following implementation will work.
> 
> client.indices.delete( index = index_name, params={"timeout":120} )

But the document for `IndicesClient.delete()` states that there is a `timeout` parameter ("timeout – Explicit operation timeout"). How does that parameter work?

https://opensearch-project.github.io/opensearch-py/api-ref/clients/indices_client.html#opensearchpy.client.indices.IndicesClient.delete

**Comment by saimedhi** [comment]
@mle-els Implementation of timeout parameter in client.indices.delete is as stated above. 

And coming to how the parameter works, here 'timeout' helps us define "How long to wait for the response to return  while performing an operation".

**Comment by wbeckler** [comment]
@mle-els can you try invoking it dictionary-style and see if that helps?

**Comment by mle-els** [comment]
> @mle-els Implementation of timeout parameter in client.indices.delete is as stated above.
> 
> And coming to how the parameter works, here 'timeout' helps us define "How long to wait for the response to return while performing an operation".

I mean what/how should I pass into it? The doc contains "index" and "timeout" in the same list so I interpret that we can pass "timeout" the same way as we pass "index". But when I pass an int (`timeout=120`), it throws an error.

**Comment by mle-els** [comment]
> @mle-els can you try invoking it dictionary-style and see if that helps?

It didn't throw an error so it seems to help. I didn't manage to check if it actually times out though.

**Comment by mle-els** [comment]
As far as I understand, two ways of passing parameters are supported (that's the job of the `query_params()` decorator). The bug here is that one method doesn't work, specifically in the case of "timeout".

**Comment by wbeckler** [comment]
The "params" parameter is very poorly named, as it is a dictionary of parameters that are sent along to the server. I don't think there's a separate invocation style a la kwargs.

**Comment by calebplum** [comment]
I ran into this problem as well. Can the documentation please be updated to reflect the current state of this feature? I don't think users should necessarily have to dig through the source code to find the correct information.

**Comment by wbeckler** [comment]
Feel free to craft a PR for the documentation update if you're up for it.
