### ISSUE TITLE
[BUG] Cannot import AsyncOpenSearch in Linux Container

### ISSUE THREAD

**Issue by cdobbsTM** [opensearch-project/opensearch-py#281]
### What is the bug?
`ImportError: cannot import name 'AsyncOpenSearch' from 'opensearchpy' (/app/.local/lib/python3.9/site-packages/opensearchpy/__init__.py)` when running within a Linux Docker container

### How can one reproduce the bug?
1. Create Docker image from ubi8 base image
2. Install Python 3.9
3. Install opensearch-py==2.1.1
4. Run "from opensearchpy import AsyncOpenSearch" from within container

### What is the expected behavior?
The AsyncOpenSearch client to be successfully imported

### What is your host/environment?
Windows 10, RedHat ubi8 container

### Do you have any screenshots?
Not necessary 

### Do you have any additional context?
When I run my project outside of Docker it works fine.

Code from `opensearchpy\__init__.py`:
```
try:
    # Asyncio only supported on Python 3.6+
    if sys.version_info < (3, 6):
        raise ImportError

    from ._async.client import AsyncOpenSearch
    from ._async.http_aiohttp import AIOHttpConnection, AsyncConnection
    from ._async.transport import AsyncTransport
    from .connection import AsyncHttpConnection

    __all__ += [
        "AIOHttpConnection",
        "AsyncConnection",
        "AsyncTransport",
        "AsyncOpenSearch",
        "AsyncHttpConnection",
    ]
except (ImportError, SyntaxError):
    pass
```
I imagine this code might have something to do with the issue but I don't see why it would skip the imports when running on Python 3.9.

**Comment by cdobbsTM** [comment]
#96 I can see that this issue mentions the same problem.

Trying `opensearch-py[async]==2.1.1`. 

Although I don't see why there is a change in behaviour between installing into a container vs on the host machine.

**Comment by cdobbsTM** [comment]
The above resolved this but I can't see it documented anywhere.

**Comment by wbeckler** [comment]
Would you be up for submitting a documentation PR?
