### ISSUE TITLE
[FEATURE] Index State Management support

### ISSUE THREAD

**Issue by kinoute** [opensearch-project/opensearch-py#284]
### Is your feature request related to a problem?

I would like to [create/add index policy](https://opensearch.org/docs/latest/im-plugin/ism/api/#create-policy) in the Index State Management but couldn't find a way to do it.

### What solution would you like?

Support The index state management to create policies.

### What alternatives have you considered?

I tried the official ElasticSearch which supports [the feature](https://elasticsearch-py.readthedocs.io/en/v7.17.9/api.html#elasticsearch.client.IlmClient.put_lifecycle) through the use of a `ilmClient` instance and the `put_lifecycle` method. But it doesn't work with OpenSearch because it tries to create policies in `/_ilm/policy/abc` which doesn't exist in OpenSearch:

```
no handler found for uri [/_ilm/policy/abc] and method [PUT]',
 'no handler found for uri [/_ilm/policy/abc] and method [PUT]')
```

**Comment by wbeckler** [comment]
This is a good idea. Most of the plugins are unsupported via methods in the client, so developers end up writing raw curl requests and sending those like this (not in python):
```
PUT _plugins/_ism/policies/policy_id
{
  "policy": {
    "description": "Example policy.",
    "default_state": "...",
    "states": [...],
    "ism_template": {
      "index_patterns": ["index_name-*"],
      "priority": 100
    }
  }
}
```

There is a larger question of how to support plugins in clients. In OpenSearch, there is no such thing as an "ilmClient." 

I think one of the visions for OpenSearch is to be more extensible and flexible than its predecessor, which means it should be easy to add in this kind of functionality. And we should expect an increasing number of plugins/extensions.

Where do you think this functionality should go for the python client?

**Comment by wbeckler** [comment]
I should also mention that someone started this conversation about how to architect this here: https://github.com/opensearch-project/opensearch-py/issues/90

**Comment by kinoute** [comment]
For those who are interested, I forked the ElasticSearch Python library to support the creation of ISM/ISLM policies and it works:

https://github.com/kinoute/elasticsearch-py/blob/7.11/elasticsearch/client/ilm.py#L111-130

**Comment by wbeckler** [comment]
Feel free to contribute any code to this repo that you write or find, as long as its license is compatible (e.g., Apache 2.0).

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-py/pull/398
