### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#289]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by harshavamsi** [comment]
@dblock @wbeckler the MAINTAINERS and CODEOWNERS looks right to me. As admins can you verify the github settings are also accurate and close this issue?

**Comment by wbeckler** [comment]
I checked the permissions and they match.

**Comment by dblock** [comment]
Verified actual permissions, thanks.
