### ISSUE TITLE
AttributeError: 'AggsProxy' object has no attribute '_index'

### ISSUE THREAD

**Issue by bepetersn** [opensearch-project/opensearch-py#299]
This is probably not a bug on second glance, I must just be using the library incorrectly. Would love to receive that feedback. I am pretty new to this library as I am maintaining some legacy code. 

This is (obviously) not on you, but for total context, this code worked before, in the sense that it didn't produce error at least, when I was using `elasticsearch_dsl` (version 6 -- with accompanying ESv6 product), but after upgrading, is causing a unittest failure with this error / code. I had to remove a reference to `.aggs` at line ~17 of the below code snippet on the rv of the first `metric()` call, where the comment with `****` is located, before getting _this_ error.

**What is the bug?**
Error with using aggregations:
`AttributeError: 'AggsProxy' object has no attribute '_index'`

**How can one reproduce the bug?**
_Steps to reproduce the behavior:_
I know this isn't enough, but it's a start...

```python
from opensearch_dsl import Search, MultiSearch
from opensearch_dsl.query import Match, Terms, Term

rides = Search(using=client, index="rides")
ms = MultiSearch(using=client, index=index_name)
ms = ms.add(rides.filter(Term(normal_status=a)).extra(size=0))
ms = ms.add(rides.filter(Term(status=b)).extra(size=0))
ms = ms.add(rides.filter(Term(normal_status=c)).extra(size=0))
ms = ms.add(
    rides.filter(Terms(normal_status=[x, y, z])).extra(
        size=0
    )
)
ms = ms.add(
    rides.aggs
    .metric(                         
        "total_cost_incurred", "sum", field="cost_dollars"
    )                     # ****
    .metric(
        "cancellation_cost_incurred", "sum", field="cancellation_cost"
    )
)
responses = ms.execute()
```

**What is the expected behavior?**
I expect the `execute()` statement not to error out, at least.

**What is your host/environment?**
 - I am using this dockerhub image: `opensearchproject/opensearch:1.2.4`
 - OS: Amazon Linux 2
 - opensearch-dsl==1.0.0
 - opensearch-py==1.1.0

**Do you have any additional context?**
Traceback:
```python
    responses = ms.execute()
  File "/Users/brian.peterson/project/venv/lib/python3.7/site-packages/opensearch_dsl/search.py", line 811, in execute
    index=self._index, body=self.to_dict(), **self._params
  File "/Users/brian.peterson/project/venv/lib/python3.7/site-packages/opensearch_dsl/search.py", line 794, in to_dict
    if s._index:
  File "/Users/brian.peterson/project/venv/lib/python3.7/site-packages/opensearch_dsl/utils.py", line 341, in __getattr__
    self.__class__.__name__, name
AttributeError: 'AggsProxy' object has no attribute '_index'
```

Anything else short of a full repro that would be of use? The index / mapping itself maybe?

**Comment by VachaShah** [comment]
Transferring this issue here as opensearch-dsl-py is being merged into opensearch-py as part of #194

**Comment by wbeckler** [comment]
@bepetersn your issue hasn't gotten traction for a while. Is it still of interest to you? Would you have any more context to share that you've gleaned since then?

**Comment by saimedhi** [comment]
please reopen the issue, if you think the bug still exists.
