### ISSUE TITLE
[CCI][BUG] Test coverage statistics are not displayed correctly

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-py#315]
### What is the bug?
The project is integrated with codecov.io , however, coverage graphs [here](https://app.codecov.io/gh/opensearch-project/opensearch-py) are not displayed. 

### How can one reproduce the bug?
Follow this link: [codecov.io/opensearch-project/opensearch-py](https://app.codecov.io/gh/opensearch-project/opensearch-py)

### What is the expected behavior?
It is necessary to complete the integration with codecov. Visualization of test coverage has already been implemented in [many other repositories](https://app.codecov.io/gh/opensearch-project/opensearch-js), so this project should not be an exception.

### Do you have any screenshots?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57720347/223426855-ccd70bc5-f043-422d-b8d2-14ae3b13bbbb.png">

Related Issue: #105

**Comment by bl1nkker** [comment]
I would like to address this issue if possible.

**Comment by dblock** [comment]
@bl1nkker No need to ask for permission, just do it! And thank you!
