### ISSUE TITLE
[CCI][BUG] Test support required for Python v3.9+

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-py#323]
### What is the bug?
When running test suite tests don't run for python 3.9+

### How can one reproduce the bug?
1. Install Python 3.9+
2. Run the `nox -rs test` command

### What is the expected behavior?
If you don't have the version specified in noxfile.py, all tests will be skipped:

nox > * test-2.7: failed
nox > * test-3.4: skipped
nox > * test-3.5: skipped
nox > * test-3.6: skipped
nox > * test-3.7: skipped
nox > * test-3.8: skipped
nox > * test-3.9: skipped

### What is your host/environment?
OS: macOS
Python: v3.10.4

**Comment by bl1nkker** [comment]
I also noticed before that version 2 is no longer supported. Should it be removed from noxfile?

**Comment by wbeckler** [comment]
Makes sense. As for version 2, I don't see why we wouldn't remove it.
