### ISSUE TITLE
[BUG] Unable to import AsyncOpenSearch from opensearch-py v2.2.0

### ISSUE THREAD

**Issue by elamirKad** [opensearch-project/opensearch-py#332]
### What is the bug?
I tried to replicate the code from this issue [#172](https://github.com/opensearch-project/opensearch-py/issues/172) and encountered a problem when trying to import AsyncOpenSearch.
`ImportError: cannot import name 'AsyncOpenSearch' from 'opensearchpy' (C:\Users\elami\.virtualenvs\testing-opensearch\lib\site-packages\opensearchpy\__init__.py)`

### How can one reproduce the bug?

1. Install the opensearch-py library using `pip install opensearch-py` or `pip install --upgrade opensearch-py`.
2. Try to import the AsyncOpenSearch class using the following import statement:
`from opensearchpy import AsyncOpenSearch`

### What is the expected behavior?
The AsyncOpenSearch class should be imported successfully without any issues.

### What is your host/environment?
Tested both on Windows 11 and Ubuntu 22.04

### Do you have any screenshots?
Not applicable.

### Do you have any additional context?
I have the following opensearch-py library version installed:

> Name: opensearch-py
> Version: 2.2.0
> Summary: Python client for OpenSearch
> Home-page: https://github.com/opensearch-project/opensearch-py
> Author: Aleksei Atavin, Denis Zalevskiy, Rushi Agrawal, Shephali Mittal
> Author-email: axeo@aiven.io, dez@aiven.io, rushi.agr@gmail.com, shephalm@amazon.com
> License: Apache-2.0
> Location: c:\users\elami\.virtualenvs\testing-opensearch\lib\site-packages
> Requires: certifi, python-dateutil, requests, six, urllib3
> Required-by:

Python version on Ubuntu: 3.8.10
Python version on Windows: 3.10.7

Despite installing and upgrading the library, the import issue persists.

**Comment by margulanz** [comment]
```pip install aiohttp```, then try import again. Let me know if it works.

**Comment by elamirKad** [comment]
@margulanz thanks! It worked like a charm.

**Comment by dblock** [comment]
Do we have a bug/problem in opensearch-py?
