### ISSUE TITLE
[PROPOSAL][CCI] Document docker setup in DEVELOPER_GUIDE.md

### ISSUE THREAD

**Issue by roma2023** [opensearch-project/opensearch-py#341]
### What are you proposing?
To complement the DEVELOPER_GUIDE.md by specifying the details for running the project on Docker.

### What problems are you trying to solve?
Quite a few contributors having trouble with setting up Docker and running it for integration  

@Eager-coder and I would love to work on this issue.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-py/pull/427
