### ISSUE TITLE
[BUG] "track_total_hits":"true" has no effect

### ISSUE THREAD

**Issue by MadhavVij** [opensearch-project/opensearch-py#343]
### What is the bug?
Adding search Param `"track_total_hits":"true"` doesn't reflect `eq` relation and still shows `gte` relation for results more than 10k.

### How can one reproduce the bug?
Add the track_total_hits to search param by:

    search_object = search_object.params(
        track_total_hits=True
    )

### What is the expected behavior?
If `track_total_hits` is set to true, we should get the actual number of documents in `hit_count` and not the 10k limit with `gte` relation.

### What is your host/environment?
AWS Opensearch 2.3

### Do you have any screenshots?
No

### Do you have any additional context?
The query works, if I do a manual query on kibana interface in Opensearch cluster.
Example query that works on kibana but not through opensearch-py library:

    GET _search
    {
        "track_total_hits":true,
        "query": {
            "wildcard": {
                 "_id": {
                      "value": "*"
                }
            }
        }
    }

**Comment by matthewdeanmartin** [comment]
I also verified that even if you pass the track_total_hits argument to the OpenSearch() client, that the eventual response still only reports 10,000 hits, even though you can page beyond the 10,000.

**Comment by harshavamsi** [comment]
Hi @MadhavVij, thanks for the issue. Pinging @saimedhi to investigate further.

**Comment by MadhavVij** [comment]
@harshavamsi  @saimedhi  I was able to get it running.
The `track_total_hits` needs to be set as in `Search().extra()` parameter and not in `Search().param()`. The following code worked for me:

    search_object = search_object.extra(track_total_hits=True)

It would be great if this can be documented somewhere, but I am closing the issue, since it doesn't need any fixes.
