### ISSUE TITLE
[Guide] Index Template

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-py#351]
Create `guides/index_template.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/index_template.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by Zhandoszzz** [comment]
Can I work on this issue?

**Comment by nhtruong** [comment]
Of course. And Thank you :)

**Comment by Temirlan-qa** [comment]
Can I work on this issue?

**Comment by nhtruong** [comment]
@Temirlan-qa looks like @Zhandoszzz is already working on it

**Comment by Temirlan-qa** [comment]
@nhtruong Ok. Got it

**Comment by Djcarrillo6** [comment]
Hi @nhtruong, I'm in the OSCI & Sai Medhini recently mentioned in the osci-clients Slack channel that there are many good first issues to work on in the Python client.

If it's okay with you, I'd like to request assignment on this issue. I just opened a PR for this same index template guide in the .NET client [here](https://github.com/opensearch-project/opensearch-net/pull/392), and given that I think this could be a good issue for me to wrap up on the Python client as well.

**Comment by nhtruong** [comment]
I've assigned you to this issue.  Thanks for taking over. @saimedhi is in charge of this Repo BTW. Feel free to contact her regarding issues in this repo as well

**Comment by tannerjones4075** [comment]
Should this issue be closed? It looks like there was a merge.

**Comment by Djcarrillo6** [comment]
Yes that's correct, my PR to fix it was just merged.
