### ISSUE TITLE
[Guide] Document Lifecycle

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-py#352]
Create `guides/document_lifecycle.md` similar to the [Ruby guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/document_lifecycle.md)

You must assure that: 
- All code-blocks, when run from start to finish in order they appear in the guide, do not throw any errors. If you want to demonstrate that certain statements will throw errors, they must be wrapped in a `try/catch` and print out the expected error.
- All code-blocks are properly marked with the language it's written in (i.e.  ` ```ruby `)
- The instructions, though mostly identical to the Ruby guide, are suitable for this repo.

**Comment by Nicksqain** [comment]
@nhtruong I have made a PR to solve this issue #364

**Comment by tannerjones4075** [comment]
Have this issue been resolved? It looks like #364 has been resolved.

**Comment by saimedhi** [comment]
Hello @Nicksqain,

Would you like to co-author #364 with @tannerjones4075 or handle it on your own?

Thank you.

**Comment by saimedhi** [comment]
@tannerjones4075, go ahead and finish the PR (including working sample) if you are interested :)

**Comment by Djcarrillo6** [comment]
Hi @saimedhi if it's okay with you(and @tannerjones4075), I'd like to request assignment on this. I've been working on the API guides recently anyway & I can probably get this wrapped up by Friday.

**Comment by dblock** [comment]
Closing via https://github.com/opensearch-project/opensearch-py/pull/559.
