### ISSUE TITLE
Add API Guides

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-py#355]
(Spawn off of meta Issue: https://github.com/opensearch-project/opensearch-clients/issues/56)
To help drive adoption of OpenSearch, and improve user's experience, we're working on adding more documentation for all clients. One of the strategies mentioned in said issue is writing a collection of articles serving as a User's Guide for each client. This issue will serve as a hub for all issues related to this topic.

Each Guide/Article will be a `good-first-issue` for new contributors to work on. There's already a Ruby version of each article that the articles on this repo should be based upon. Most of the time, we only need to replace the Ruby code blocks with the client code of this repo. Please refer to the [meta issue](https://github.com/opensearch-project/opensearch-clients/issues/56) for more details.

- [x] https://github.com/opensearch-project/opensearch-py/issues/349
- [x] https://github.com/opensearch-project/opensearch-py/issues/350
- [x] https://github.com/opensearch-project/opensearch-py/issues/351
- [x] https://github.com/opensearch-project/opensearch-py/issues/352
- [x] https://github.com/opensearch-project/opensearch-py/issues/353
- [x] https://github.com/opensearch-project/opensearch-py/issues/354

**Comment by dblock** [comment]
All these guides were done, closed.
