### ISSUE TITLE
Allow passing `trust_env` to `aiohttp.ClientSession`

### ISSUE THREAD

**Issue by michaeloliverx** [opensearch-project/opensearch-py#368]
### Is your feature request related to a problem?

I want to pass `trust_env=True` to the `aiohttp.ClientSession` here:
https://github.com/opensearch-project/opensearch-py/blob/03b72c3c929445b979560e5a2d730a83c0ba35d5/opensearchpy/_async/http_aiohttp.py#L356-L366

This will allow allow proxy configuration via `HTTPS_PROXY` environment variables.
See https://docs.aiohttp.org/en/latest/client_advanced.html?highlight=proxy#proxy-support

### What solution would you like?

`AsyncOpenSearch` to accept the `trust_env` keyword argument and pass it onto the connection class.

**Comment by Temirlan-qa** [comment]
@michaeloliverx I have made a PR to solve this issue [372](https://github.com/opensearch-project/opensearch-py/pull/372)
