### ISSUE TITLE
[BUG] async client with basic http_auth results throw an error (TypeError) #283

### ISSUE THREAD

**Issue by GRomR1** [opensearch-project/opensearch-py#384]
### What is the bug?
May be it is similar to https://github.com/opensearch-project/opensearch-py/issues/283

When testing async client with basic auth (login and password auth):
```
client = AsyncOpenSearch(
  hosts=[{
    'host': OS_HOST,
    'port': OS_PORT
  }],
  http_auth=(OS_USER, OS_PASSWORD),
  use_ssl=True,
  verify_certs=True,
  connection_class=AsyncHttpConnection,
  timeout=30
)
```
I have catch an error:
```
  File ".../opensearch_async.py", line 125, in wait_for_start
    response = await self.cluster.health(wait_for_status=status)
  File ".../venv/lib/python3.10/site-packages/opensearchpy/_async/client/cluster.py", line 78, in health
    return await self.transport.perform_request(
  File "../venv/lib/python3.10/site-packages/opensearchpy/_async/transport.py", line 374, in perform_request
    status, headers_response, data = await connection.perform_request(
  File "../venv/lib/python3.10/site-packages/opensearchpy/connection/http_async.py", line 196, in perform_request
    **self._http_auth(method, url, query_string, body),
TypeError: 'str' object is not callable
```

### How can one reproduce the bug?
Initialize and use AsyncOpenSearch client with basic http_auth (i.e with use [OS on docker](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/) for example) and make a call to `info()`

### What is the expected behavior?
Successful response the information from OS.

### What is your host/environment?
OS: 12.6.5
Python: 3.10.11
opensearch-py: 2.2.0

### Do you have any additional context?
I think there is a simple mistake in code. Was forgotten `http_auth` argument in init block:
- https://github.com/opensearch-project/opensearch-py/blob/05326ba5474c1a1f5c1975760a4e37037f967dda/opensearchpy/connection/http_async.py#L56-L65
And this should be removed:
- https://github.com/opensearch-project/opensearch-py/blob/05326ba5474c1a1f5c1975760a4e37037f967dda/opensearchpy/connection/http_async.py#L193-L196

I've create a PR

**Comment by saimedhi** [comment]
Hello @GRomR1, I attempted to reproduce this issue but couldn't observe any problems. Please refer to the [guide](https://github.com/opensearch-project/opensearch-py/blob/main/guides/async.md) for assistance. If you encounter any further issues, please don't hesitate to reopen this matter. Thank you!
