### ISSUE TITLE
[PROPOSAL] Replace dependency management and nox with poetry

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#392]
### What are you proposing?

There are too many layers of bash scripts and dev requirements in this project. I propose to replace those with poetry, which we already use in samples.

### What users have asked for this feature?

Any sane developer ;)

### What problems are you trying to solve?

It should be trivial to get started coding in this project.

### What is the developer experience going to be?

Similar to https://github.com/opensearch-project/opensearch-build/blob/main/DEVELOPER_GUIDE.md#install-prerequisites.

1. Install Python.
2. Run `pip install pipenv ` then `pipenv install`.
3. Run `pipenv run pytest` to run tests.

**Comment by tsabbir96** [comment]
Hi @dblock just a thought, will using poetry prove any more beneficial other than using pipenv?

**Comment by dblock** [comment]
@tsabbir96 I personally haven't worked with poetry, so I don't know and don't have strong preferences. In general I think it's worth replacing virtualenv setup by a tool, which is what this issue is about - we can look at the code diff to see whether it's better or not once someone takes it on.

**Comment by tsabbir96** [comment]
@dblock I totally agree with you, not using a setup tool can lead to frustrating scenarios while manually taking care of the setup. If it is decided which tool can be used for this project, I would be glad to contribute by integrating the tool into this project

**Comment by dblock** [comment]
Thanks @tsabbir96! If you have copious free time (TM) you could implement both pipenv and poetry, compare and write a blog post on your blog about the pros and cons of each linking both PRs! :)

**Comment by roma2023** [comment]
Can I take this issue up? Can you please assign it to me?

**Comment by dblock** [comment]
@roma2023 I just assigned a couple of others to you, please feel free to pickup any of them, no need for assignments!

**Comment by roma2023** [comment]
I just read above that this issue will serve as a prerequisite to #393 and I was thinking it'd probably be better to start tackling this one first.

**Comment by dblock** [comment]
I wrote some samples recently in https://github.com/opensearch-project/opensearch-py/tree/main/samples, and needed a way to reliably reference source code in the repo rather than a released version of opensearch-py. I used [poetry](https://python-poetry.org/) quite successfully, and I think we should go with that for this issue.

**Comment by dblock** [comment]
I POCed this in https://github.com/opensearch-project/opensearch-py/pull/580, and I am convinced it's not better.

Pros: merges setup.py, dev-requirements.txt, and setup.cfg
Cons: introduces another tool in the middle called from nox

I think nox already creates a stable-enough virtual environment and we had been slowly moving all commands and tools under it (such as `nox -rs lint` or `nox -rs test-3.9`), so poetry becomes redundant.
