### ISSUE TITLE
[BUG] resources ported from opensearch-dsl-py causing mypy errors

### ISSUE THREAD

**Issue by morrissimo** [opensearch-project/opensearch-py#402]
### What is the bug?
At least some of the resources ported into opensearch-py from the opensearch-dsl-py project cause mypy errors

### How can one reproduce the bug?
```
$ mkdir sample_app
$ (create & activate a new virtualenv - I use pyenv, so "pyenv virtualenv 3.8.15 sample-app")
$ pip install opensearch-py mypy
$ mkdir sample_app
$ touch sample_app/__init__.py sample_app/app.py
```
Contents of `sample_app/app.py`:
```python
from opensearchpy import OpenSearch
from opensearchpy.helpers.response import Response
from opensearchpy.helpers.search import Search


# adapted from https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md#creating-a-client
host = 'localhost'
port = 9200
auth = ('admin', 'admin') # For testing only. Don't store credentials in code.

client = OpenSearch(
    hosts = [{'host': host, 'port': port}],
    http_compress = True, # enables gzip compression for request bodies
)

def do_search(match_term: str) -> Response:
    # adapted from https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md#searching-for-documents-with-filters
    # Search for the document.
    s = Search(using=client, index="my_index") \
        .filter("term", category="search") \
        .query("match", title="python") \
        .extra(track_total_hits=True)

    response = s.execute()

    print('\nSearch results:')
    for hit in response:
        print(hit.meta.score, hit.title)

    return response
```

Running mypy produces the following output:
```
$ mypy sample_app/
sample_app/app.py:19: error: Unexpected keyword argument "using" for "Search"  [call-arg]
sample_app/app.py:19: error: Unexpected keyword argument "index" for "Search"  [call-arg]
sample_app/app.py:19: error: "Search" has no attribute "filter"  [attr-defined]
Found 3 errors in 1 file (checked 2 source files)
```

### What is the expected behavior?
I would expect mypy to pass without errors for opensearch-py resources - especially resources that do in fact work as documented

### What is your host/environment?
* Mac OSX Ventura 13.3.1 (Intel, 2019 Macbook Pro)
* python 3.8.15
* pip 22.0.4
* mypy 1.3.0
* opensearch-py 2.2.0

### Do you have any screenshots?
n/a

### Do you have any additional context?
This issue was discovered when I ported an application to use the latest version of opensearch-py and updated our code to no longer use opensearch-dsl-py

I have directly observed mypy reporting issues for the following resources:
```python
from opensearchpy.helpers.response import Response
from opensearchpy.helpers.search import Search
from opensearchpy.helpers.utils import AttrDict
```

**Comment by saimedhi** [comment]
Hello @morrissimo, Thanks for letting us know. I will take a look at this issue.

**Comment by saimedhi** [comment]
@morrissimo, I have tested the code in VSCode and observed accurate responses. Could the error be specific to using opensearch-py with mypy and Pyenv?

```
index_name = 'my-dsl-index'
response = client.indices.create(index_name)
print('\nCreating index:')
print(response)

document = {
    'title': 'python',
    'description': 'beta',
    'category': 'search'
}
id = '1'

response = client.index(
    index = index_name,
    body = document,
    id = id,
    refresh = True
)
print('\nAdding document:')
print(response)


# Search for the document.
s = Search(using=client, index=index_name) \
    .filter("term", category="search") \
    .query("match", title="python")

response = s.execute()

print('\nSearch results:')
for hit in response:
    print(hit.meta.score, hit.title)
```

**Comment by morrissimo** [comment]
Oh that's a good point, and one that I should have clarified in my initial write-up: the observed _functionality_ of the ported resources is correct - Search, Response, etc all work as intended and documented. The only issue I observed was specifically with the typing for the ported resources.

What output did mypy produce for your test module?

pyenv + mypy: I suppose it's possible, but as I'm using pyenv and mypy with quite a few other packages, it does seem less likely. I'll try my test scenario again with a non-pyenv set up to verify.

**Comment by morrissimo** [comment]
> What output did mypy produce for your test module?
@saimedhi

**Comment by saimedhi** [comment]
@morrissimo, I got the same error using mypy. 

`mypy issue_402.py  
`
```
issue_402.py:57: error: Unexpected keyword argument "using" for "Search"  [call-arg]
issue_402.py:57: error: Unexpected keyword argument "index" for "Search"  [call-arg]
issue_402.py:57: error: "Search" has no attribute "filter"  [attr-defined]
```

**Comment by adambregenzer** [comment]
@saimedhi I can confirm that the pyi files for this project are incomplete and it's causing mypy to fail. As an example the `Response` object has this type hint:
``python
class Response(AttrDict): ...
```

Which doesn't include hints for `success`, `hits`,  `aggregations`, or `aggs`. This is breaking out CI/CD pipeline and our code since we rely on typing + pydantic in our api.

The easiest workaround for now would be to remove the `pyi` files and, like the opensearch_dsl package, leave it untyped until proper typing hints can be created or the code itself can be typed.

**Comment by mlachowski-mrx** [comment]
I'm facing similar issue with types as both PyCharm and mypy is not recognizing correct arguments or for example `connections` module with `get_connection` or `create_connection` methods.

![image](https://github.com/opensearch-project/opensearch-py/assets/112694412/8af59f11-9845-4430-a3a2-c3b60ade94e6)

**Comment by saimedhi** [comment]
Please feel free to take up this issue and raise a PR with your proposed solution.

**Comment by dblock** [comment]
I may have fixed this in https://github.com/opensearch-project/opensearch-py/pull/563, anyone care to help confirm?

**Comment by dblock** [comment]
Going to close. Please reopen if you feel like this is still a problem.

**Comment by bkhant1** [comment]
I had that issue and it's now fixed indeed!
