### ISSUE TITLE
[FEATURE] Add a `collapse` method to `opensearchpy.helpers.search.Search`

### ISSUE THREAD

**Issue by qcoumes** [opensearch-project/opensearch-py#408]
### Is your feature request related to a problem?
The only way to currently add a *collapse* requirement to a search body is to use the `extra()` method. This is not the cleanest way because as mentioned in its docstring, `extra()` is mostly here for backward compatibility.

### What solution would you like?
A solution would be to treat it the same way as `sort`:
* Add a `collapse()` method `opensearchpy.helpers.search.Search` which creates and stores the `dict` in a `self._collapse` attribute.
* Add `self._collapse`, if defined, in the body of the request in the `to_dict()` method.

**Comment by wbeckler** [comment]
I can't see anything of this sort, but just in case I'm missing something, I'll ask: can you think of any case, in which this is implemented, in which we would inadvertently break someone's working code?

**Comment by qcoumes** [comment]
I think the addition of a method and a "private" attribute on `Search` should not break anybody's working code.

**Comment by wbeckler** [comment]
okay, let's do it! @qcoumes if you want to take a crack at it, go for it.

**Comment by qcoumes** [comment]
I opened a PR: #409

**Comment by qcoumes** [comment]
Completed in #409

**Comment by CorneeSean** [comment]
Hello,
we just switched to AsyncOpenSearch and it seems that AsyncSearch lacks `collapse` feature altogether:
https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/helpers/search.py

**Comment by dblock** [comment]
I reopened https://github.com/opensearch-project/opensearch-py/issues/769.
