### ISSUE TITLE
[FEATURE] Preventing Proxy-Authorization Header Leak and Redirect handling Improvement

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#417]
### Is your feature request related to a problem?
Please go through the links given in additional context. 

### What solution would you like?
Enhance request handling to prevent Proxy-Authorization Header Leakage during redirects. Capture 3xx response codes and ensure a new request is made to the redirected destination to enhance security.

### What alternatives have you considered?
Please suggest any possible alternatives in the comments. 

### Do you have any additional context?
[link](https://github.com/advisories/GHSA-j8r2-6x86-q33q) to the issue and related [PR](https://github.com/opensearch-project/opensearch-py/pull/401 )

**Comment by dblock** [comment]
Resolved via https://github.com/opensearch-project/opensearch-py/pull/401.
