### ISSUE TITLE
[BUG] flaky tests due to OpenSearch repository fetch timing out

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#422]
### What is the bug?
Flaky tests in the integration test suite caused by intermittent failures in fetching the OpenSearch repository during test execution. 

### Do you have any screenshots?
<img width="1445" alt="Screenshot 2023-06-21 at 11 59 49 AM" src="https://github.com/opensearch-project/opensearch-py/assets/117196660/6b677c62-b4e7-4404-85b4-77e0735f6193">

**Comment by saimedhi** [comment]
This issue still exists as seen in  https://github.com/opensearch-project/opensearch-py/actions/runs/6089858159/job/16523525438.     

Please feel free to take up this issue and raise a PR with your proposed solution.

**Comment by prabhupant** [comment]
I would like to work on this issue. @saimedhi Can you please tell me how to run the tests locally? I cloned the repo and installed dev-requirements, then in the `test-opensearch` repo, I tried running `python3 run_tests.py` but I am getting this error 

```
File "/Users/prabhu/personal/opensearch-py/test_opensearchpy/run_tests.py", line 68, in fetch_opensearch_repo
    from test_opensearchpy.test_cases import SkipTest
ModuleNotFoundError: No module named 'test_opensearchpy'
```

Please let me know if I am doing something wrong

**Comment by dblock** [comment]
@prabhupant Check out https://github.com/opensearch-project/opensearch-py/blob/main/DEVELOPER_GUIDE.md, I believe `nox -rs ...` will setup the right environment for you.

**Comment by prabhupant** [comment]
@dblock Thanks! Seems to be working now. Just one more question. I am getting this error when I am running `nox -rs test-3.10`

```
File "/Users/prabhu/personal/opensearch-py/opensearchpy/connection/http_urllib3.py", line 283, in perform_request
    raise SSLError("N/A", str(e), e)
opensearchpy.exceptions.SSLError: ConnectionError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)) caused by: SSLError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997))
```

I think this is because my OpenSearch instance in Docker is running without TLS and the requests to OpenSearch expects an http endpoint but from a couple of places in the test cases we are using https. If my assumption is correct, is there any way to make all the test requests call OpenSearch without TLS, or shall I setup certificate check in my local instance of OpenSearch?

**Comment by saimedhi** [comment]
- Hey @prabhupant, check out the guide [here](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#run-opensearch-in-a-docker-container) to run OpenSearch in a Docker container:
```
docker pull opensearchproject/opensearch:2.11.1
docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:2.11.1
```

- Additionally, I've noticed that this issue pertains to [integration tests](https://github.com/opensearch-project/opensearch-py/blob/main/DEVELOPER_GUIDE.md#running-tests), which can be executed using `./.ci/run-tests false 2.11.1`
  Note: Please remember to stop the running OpenSearch container before running "./.ci/run-tests true 2.11.1", as it will start the OpenSearch container as part of the test suite.

- Also, if you're interested, take a peek at this issue: [opensearch-project/opensearch-py#393](https://github.com/opensearch-project/opensearch-py/issues/393). It's pertinent to the current topic; ideally, when running unit tests, an OpenSearch instance isn't necessary. However, currently, an OpenSearch instance is required for unit tests to run.

**Comment by dblock** [comment]
Please do improve these tools/scripts/guides!

**Comment by prabhupant** [comment]
Sure @dblock! I have been using opensearch-py as part of my work and have made a few commits in the doc repo. Planning to start contributing here on my free time

**Comment by prabhupant** [comment]
@saimedhi I tried running `./.ci/run-tests false 2.11.1` 7-8 times but I never ran into this error. Even tried this with my VPN on. Could you please tell how can I replicate this?

**Comment by saimedhi** [comment]
Hello @prabhupant! I haven't encountered this flaky test for a few months, and the [link](https://github.com/opensearch-project/opensearch-py/actions/runs/6089858159/job/16523525438.) to the failed test log in this issue appears to be expired. I'm not sure if we can replicate this issue, but I'll investigate it. Feel free to explore other issues like #393  in the meantime.

**Comment by dblock** [comment]
If we haven't seen flakes for a long time, maybe we can close this until we see one?
