### ISSUE TITLE
[PROPOSAL] Release v. Next

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#432]
### What are you proposing?

Release v. Next

### What users have asked for this feature?
https://github.com/opensearch-project/opensearch-py/pull/378#issuecomment-1626076827

**Comment by WhipSnake23** [comment]
Please make a release. So many features that are not in the release made in march. Its confusing why there are not more frequent releases with all the features being added.

**Comment by saimedhi** [comment]
I am working on the release. Just a few more things to be done before it. Thank you for the patience.
