### ISSUE TITLE
[FEATURE] Support OpenSearch 2.7+

### ISSUE THREAD

**Issue by thaotruong-aws** [opensearch-project/opensearch-py#441]
### Is your feature request related to a problem?

Latest versions of OpenSearch (2.7+) not supported.

### What solution would you like?

Support for OpenSearch 2.7+.

### What alternatives have you considered?

We can use plain requests library, but it would be convenient to have Python client support instead.

### Do you have any additional context?

We have upgraded our OpenSearch clusters to version 2.7 (latest allowed on AWS Console) to pull in the data stream features that were added since OpenSearch 2.6. Turns out this Python client does not yet support these newer versions according to the Compatibility table.

**Comment by saimedhi** [comment]
Working on it.
