### ISSUE TITLE
[BUG] ERROR: Cannot install urllib3==2.0.4 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by vchepurko** [opensearch-project/opensearch-py#492]
### What is the bug?
ERROR: Cannot install -r requirements.txt (line 28) and urllib3==2.0.4 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested urllib3==2.0.4
    opensearch-py 2.3.1 depends on urllib3<2 and >=1.21.1

### How can one reproduce the bug?
When try to install new version of URLLIB3

### What is the expected behavior?
The latest lib of urllib3 is 2.0.4

**Comment by saimedhi** [comment]
Hello @vchepurko,

The issue has been resolved in PR #466, but it has not been released yet. If necessary, kindly create an issue for the release of version 2.3.2. Thank you :)
