### ISSUE TITLE
High level client coming soon

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#50]
Python high-level client support is in the works, and should be out soon. Keeping this ticket open to track it.

**Comment by Jeffreyx38** [comment]
Thanks. Is there a date for the release?

**Comment by command-tab** [comment]
Like ElasticSearch and OpenSearch, will the high level opensearch-dsl-py client start out as a fork of elasticsearch-dsl-py? Trying to guesstimate how much time will be involved in adopting OpenSearch in an existing ES project. Thanks! 🙏🏻

**Comment by vchrombie** [comment]
> Like ElasticSearch and OpenSearch, will the high level opensearch-dsl-py client start out as a fork of elasticsearch-dsl-py? 

Yes, it would be a fork from the elasticsearch-dsl package.

https://discuss.opendistrocommunity.dev/t/opensearch-high-level-client-library-for-python-elasticsearch-dsl-equivalent/6877/2

> Trying to guesstimate how much time will be involved in adopting OpenSearch in an existing ES project. Thanks! 🙏🏻

I would leave this question to the maintainers.

**Comment by VijayanB** [comment]
Closing this issue since opensearch-dsl-py is already released.
