### ISSUE TITLE
[FEATURE] Requesting release of version 2.3.2

### ISSUE THREAD

**Issue by lylejohnson** [opensearch-project/opensearch-py#510]
### Is your feature request related to a problem?

Yes. I ran into the problem described in [this issue](https://github.com/opensearch-project/opensearch-py/issues/464), which was apparently resolved by [this pull request](https://github.com/opensearch-project/opensearch-py/pull/466); however, that code has not yet been released.

### What solution would you like?

I'd like for the team to schedule a release of `opensearch-py` (presumably version 2.3.2) which incorporates this fix.

### What alternatives have you considered?

I'm not sure what my other options are, other than maybe installing from a patched version of the source?

### Do you have any additional context?

N/A

**Comment by IanHoang** [comment]
Releasing 2.3.2 would help OpenSearch-Benchmark with the following CVE-Risk
- https://github.com/opensearch-project/opensearch-benchmark/issues/378
