### ISSUE TITLE
[BUG] Wrong return type hint in async_scan

### ISSUE THREAD

**Issue by dmenini** [opensearch-project/opensearch-py#512]
### What is the bug?

The interface for `async_scan` (https://github.com/opensearch-project/opensearch-py/blob/2feccc22bb8300e9e0d9a4575e2717f2baec17ec/opensearchpy/_async/helpers/actions.pyi#L103C6-L103C31) suggests that the return type is `AsyncGenerator[int, None]`, while it should be `AsyncGenerator[dict, None]` since every yielded hit is a dictionary.

**Comment by saimedhi** [comment]
@dmenini, Please feel free to contribute! Thanks :)
