### ISSUE TITLE
[BUG] Integ test does a deep checkout of opensearch repository

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#52]
**What is the bug?**
[Here](https://github.com/opensearch-project/opensearch-py/blob/340069f6fa344ab3853fec8c48e60e6a7756f271/test_opensearch/run_tests.py#L49), we're doing a deep checkout of OpenSearch (the server) repository. This works reasonably fast on Github Actions, but slows down the run time considerably when doing it on a developer laptop. We should ideally do a shallow checkout i.e. `git clone --depth=1 <url>`

**How can one reproduce the bug?**
Run `./.ci/run-test opensearch true` on dev laptop (requires Docker to be installed)

**What is the expected behavior?**
The build should finish fast

**What is your host/environment?**
 - OS: MacOS Catalina

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

**Comment by vchrombie** [comment]
Hi @rushiagr, I opened a PR related to this issue. It would be great if we can discuss a few things before finalizing the work in the PR.

The shallow clone reduces a lot of time. If we specify a branch, it can be even faster. Here is a small analysis
```
p0tt3r@wand /tmp
>🔮$ time git clone https://github.com/opensearch-project/opensearch TEST_OPENSEARCH_REPO
Cloning into 'TEST_OPENSEARCH_REPO'...
remote: Enumerating objects: 1362707, done.
remote: Counting objects: 100% (1143/1143), done.
remote: Compressing objects: 100% (688/688), done.
remote: Total 1362707 (delta 365), reused 900 (delta 250), pack-reused 1361564
Receiving objects: 100% (1362707/1362707), 488.59 MiB | 8.38 MiB/s, done.
Resolving deltas: 100% (767548/767548), done.
Updating files: 100% (9998/9998), done.
git clone https://github.com/opensearch-project/opensearch   117.64s user 21.24s system 26% cpu 8:35.27 total


p0tt3r@wand /tmp
>🔮$ time git clone --depth 1 https://github.com/opensearch-project/opensearch TEST_OPENSEARCH_REPO                      
Cloning into 'TEST_OPENSEARCH_REPO'...
remote: Enumerating objects: 13178, done.
remote: Counting objects: 100% (13178/13178), done.
remote: Compressing objects: 100% (7264/7264), done.
remote: Total 13178 (delta 4802), reused 10429 (delta 4022), pack-reused 0
Receiving objects: 100% (13178/13178), 21.96 MiB | 7.72 MiB/s, done.
Resolving deltas: 100% (4802/4802), done.
Updating files: 100% (9998/9998), done.
git clone --depth 1 https://github.com/opensearch-project/opensearch   3.18s user 1.02s system 49% cpu 8.490 total


p0tt3r@wand /tmp
>🔮$ time git clone --branch main --single-branch --depth 1 https://github.com/opensearch-project/opensearch TEST_OPENSEARCH_REPO
Cloning into 'TEST_OPENSEARCH_REPO'...
remote: Enumerating objects: 13178, done.
remote: Counting objects: 100% (13178/13178), done.
remote: Compressing objects: 100% (7264/7264), done.
remote: Total 13178 (delta 4802), reused 10417 (delta 4022), pack-reused 0
Receiving objects: 100% (13178/13178), 21.96 MiB | 7.32 MiB/s, done.
Resolving deltas: 100% (4802/4802), done.
Updating files: 100% (9998/9998), done.
git clone --branch main --single-branch --depth 1  TEST_OPENSEARCH_REPO  2.93s user 1.19s system 55% cpu 7.496 total
```
Please let me know what do you prefer. I will update the PR accordingly.

**Comment by rushiagr** [comment]
Hi @vchrombie , first of all thanks for your interest and contribution to the Python client! We anyway need just one branch, so `--single-branch` would work too, and since it's faster, I would say let's go with it :)

**Comment by vchrombie** [comment]
> We anyway need just one branch, so `--single-branch` would work too, and since it's faster, I would say let's go with it :)

Awesome. Thanks for the comment @rushiagr.
The PR already has it, but I think we need to discuss about this https://github.com/opensearch-project/opensearch-py/pull/53#issuecomment-905013442.

**Comment by rushiagr** [comment]
Added my thoughts on the PR. Let's discuss on the PR further.
