### ISSUE TITLE
[PROPOSAL] Merge .pyi types inline

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#536]
### What are you proposing?

We have the codebase littered with .pyi files. Is it time to merge types into Python code?

### What problems are you trying to solve?

Updating types in multiple places is error prone.

### What is the developer experience going to be?

No more .pyi files.

**Comment by Djcarrillo6** [comment]
Hi @dblock, I'm considering taking up this issue, just have a couple clarification questions:
 
- Would this issue require someone moving all of the type information from each .pyi stub file into it's corresponding Python file? 

- Is there anything beyond that description of steps that would also needed to be done?

**Comment by dblock** [comment]
> * Would this issue require someone moving all of the type information from each .pyi stub file into it's corresponding Python file?

Probably. We don't want to lose type information.

> Is there anything beyond that description of steps that would also needed to be done?

I don't have it. I tried to express "the problem" :)

**Comment by Djcarrillo6** [comment]
Thanks @dblock! I'd like to request assignment on this issue.

**Comment by Djcarrillo6** [comment]
Hi @dblock, I'm very sorry but can I be unassigned from this issue. I think I bit off more than I can chew with respect to the difficult level of this fix. I'm going to pick another issue shortly that is more inline with my experience level with the repo.

**Comment by dblock** [comment]
Much of this change needs to be done in the client generator, so we should get https://github.com/opensearch-project/opensearch-py/pull/543 in first.

**Comment by dblock** [comment]
I have a head start on this in https://github.com/dblock/opensearch-py/tree/remove-pyi, but this is going to be quite a bit of work.

```
$ nox -rs format

Found 1590 errors in 67 files (checked 91 source files)
nox > Command mypy --strict opensearchpy/ failed with exit code 1
```

**Comment by dblock** [comment]
I finished this in https://github.com/opensearch-project/opensearch-py/pull/563. If anyone has any good reasons not to do it, speak up!
