### ISSUE TITLE
[PROPOSAL] Publish artifacts

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/opensearch-py#54]
## What kind of business use case are you trying to solve? What are your requirements?
Need to publish artifacts (as binaries, as well as to PyPI) so that it can be easily consumed by our users. 

**What is the problem? What is preventing you from meeting the requirements?**
N/A

**What are you proposing? What do you suggest we do to solve the problem or improve the existing situation?**
See above

**What are your assumptions or prerequisites?**
N/A

**What are remaining open questions?**
None

**Comment by vchrombie** [comment]
We at [GrimoireLab](https://chaoss.github.io/grimoirelab/) use a [semi-automatic system](https://github.com/vchrombie/release-process-automation#workflow) for managing releases.

Whenever a tag is pushed, github action workflow is triggered which builds the package, tests it with different python versions, and publishes it on github, PyPI, etc. Here is the [release workflow file](https://github.com/chaoss/grimoirelab-toolkit/blob/master/.github/workflows/release.yml) for reference.

Though, we cannot use the exact same file, I believe we can make use of github actions and come up with a workflow that publishes the artifacts. Would be interested to listen to your view on this. :slightly_smiling_face:

**Comment by mikeyjarvis19** [comment]
Would find this extremely useful

**Comment by stockholmux** [comment]
@rushiagr This is published (https://pypi.org/project/opensearch-py/). Can we close this?
