### ISSUE TITLE
[BUG] API documentation seems to be empty

### ISSUE THREAD

**Issue by zhou741718** [opensearch-project/opensearch-py#558]
I got the link of client API documentation, but seems like it’s empty
https://opensearch-project.github.io/opensearch-py/api-ref/clients/opensearch_client.html

**Comment by saimedhi** [comment]
Please feel free to raise a PR with fix. Thank you :)

**Comment by dblock** [comment]
Confirming that https://opensearch-project.github.io/opensearch-py/api-ref/clients/opensearch_client.html now looks good!
