### ISSUE TITLE
[BUG] IAM auth documentation issues

### ISSUE THREAD

**Issue by chjno** [opensearch-project/opensearch-py#560]
### What is the bug?
When I follow the instructions in [auth.md](https://github.com/opensearch-project/opensearch-py/blob/main/guides/auth.md), I get the following errors
```
cannot import name 'Urllib3AWSV4SignerAuth' from 'opensearchpy'
```
```
cannot import name 'RequestHttpConnection' from 'opensearchpy' 
```
```
cannot import name 'RequestsAWSV4SignerAuth' from 'opensearchpy' 
```

It seems to work when I replace instances of `Urllib3AWSV4SignerAuth` with `AWSV4SignerAuth`.

### How can one reproduce the bug?
1. Copying the example code and running it.
2. Replacing `Urllib3HttpConnection, Urllib3AWSV4SignerAuth` in line 1 with `RequestHttpConnection, RequestsAWSV4SignerAuth`.
3. Replacing `RequestHttpConnection` in line 1 with `RequestsHttpConnection`.

### What is the expected behavior?
No import errors and successful OpenSearch API requests.

**Comment by dblock** [comment]
Support for Urllib3 Sigv4 was added in https://github.com/opensearch-project/opensearch-py/pull/547 and just hasn't been released yet. Add your +1 top https://github.com/opensearch-project/opensearch-py/issues/561.
