### ISSUE TITLE
[BUG] ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x163566bf0>: Failed to establish a new connection: [Errno 8]

### ISSUE THREAD

**Issue by sunx0766** [opensearch-project/opensearch-py#567]
### What is the bug?
_I have an Amazon OpenSearch instance. When I try to connect to it with opensearchpy on a jupyter notebook .ipynb I get this error:_
```
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x163566bf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x163566bf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known)
```

### How can one reproduce the bug?
_I ran this code in a jyputer notebook.  I have an amazon OpenSearch instance that is up and running on the VPC. For the aws_opensearch_url, I got it from AWS --> Amazon OpenSearch Service --> Domains --> Domain endpoint (VPC) and copied the URL from there._

```
from opensearchpy import OpenSearch
host = 'aws_opensearch_url'
#port = 9200
auth = ('admin', 'admin') # For testing only. Don't store credentials in code.
client = OpenSearch(
    hosts = [{'host': host}],
    http_auth = auth,
    use_ssl = False,
    verify_certs = False
)
info = client.info()
print(f"Welcome to {info['version']['distribution']} {info['version']['number']}!")
```

### What is the expected behavior?
_a print statement of the version info_

### What is your host/environment?
_LangChain: 0.0.330
opensearachpy: (2, 3, 2)
OS Type: Darwin
Python Version: 3.10.13_

### Do you have any additional context?
_To double check that the instance is up and running, I ran_
`curl awe_opensearch_url -u 'username:password'`
_and I was able to get the cluster information_

_I tried changing the parameters of `use_ssl = True`, `verify_certs=True`, with or without port, all didn't work_

_I also tried with all 3 connection classes [as described in the connection_classes.md](https://github.com/opensearch-project/opensearch-py/blob/main/guides/connection_classes.md), still had no luck_

**Comment by dblock** [comment]
Let's start with a basic sample without the langchain stack? Want to try to run https://github.com/dblock/opensearch-python-client-demo?

**Comment by dblock** [comment]
I am 100% sure this is not a client problem and something to do with the host name/network, so I am going to close this.

@sunx0766 Let us know if `curl` works successfully against your server, and if so enable logging. If there's a client bug we'll reopen of course.

**Comment by Mdelaf** [comment]
For anyone else having issues to connect to their AWS OpenSearch domain, make sure that:
- The `host` is copied from your OpenSearch domain endpoint
  - Should not have the  `https://` prefix
  - Should be of the form `search-[domain-name]-[random].aos.[region].on.aws`
- The `port` is `443`
-  The `use_ssl` is set to `True`

**Comment by dblock** [comment]
@Mdelaf it would be great to update docs/guides, maybe https://github.com/opensearch-project/opensearch-py/blob/main/guides/auth.md?
