### ISSUE TITLE
[FEATURE].  API s’ to support the features as part of OpenSearch Python SDK

### ISSUE THREAD

**Issue by AnanyaBanerjee01** [opensearch-project/opensearch-py#570]
### Problem Statement 
Could you help me with the info if there are API s’ currently to support the below features as part of OpenSearch Python SDK. Creating and deleting the below resources through SDK.

- opensearch_user
- opensearch_role
- opensearch_roles_mapping

Please find below the link to the query in opensearch community 👍🏻 https://forum.opensearch.org/t/opensearch-python-sdk-api/16613?u=aspiringananya

### What solution would you like?

Please guide me in case these APIs are already available currently.

### What alternatives have you considered?

I am unable to use terraform to spin up these resources (because of our current architecture of our product) and need the help of SDK to write scripts to both create and delete the below resources.

- opensearch_user
- opensearch_role
- opensearch_roles_mapping

**Comment by dblock** [comment]
Did you close this because all the APIs you need are supported?

See https://github.com/opensearch-project/opensearch-py/tree/main/samples/security too, do contribute more code into these!

**Comment by AnanyaBanerjee01** [comment]
> Did you close this because all the APIs you need are supported?
> 
> See https://github.com/opensearch-project/opensearch-py/tree/main/samples/security too, do contribute more code into these!

yes @dblock , exactly I got them [here](https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/client/security.py)
