### ISSUE TITLE
[BUG] Publishing to pypi yields email about GPG signatures not required

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#609]
### What is the bug?

After publishing the 2.4.2 release we got this: _During your recent upload of opensearch-py to PyPI, we noticed you uploaded a GPG signature. However, support for GPG signatures has been removed from PyPI._

### How can one reproduce the bug?

Release opensearch-py.

### What is the expected behavior?

No angry emails from pypi.

### Do you have any screenshots?

![Screenshot 2023-11-19 at 6 50 52 PM](https://github.com/opensearch-project/opensearch-py/assets/542335/7a3c52ca-c7f5-42b7-950e-c15d67cbff05)

**Comment by zelinh** [comment]
We used to sign GPG signatures within the Jenkins release workflow. Since now we can release on GHA without using Jenkins workflow, this issue should be resolved. Let's keep observe and close this issue once next release is successfully published.

**Comment by dblock** [comment]
I'll close now and reopen if it comes back! Thanks @zelinh.
