### ISSUE TITLE
[FEATURE] run nox -rs generate on a cron

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#619]
### Is your feature request related to a problem?

When OpenSearch API specification is updated it requires manual labor to pickup.

### What solution would you like?

When the API spec in OpenSearch changes,automatically raise a PR with updates, daily. Could just run on a cron, copy from [this workflow](https://github.com/slack-ruby/slack-ruby-client/blob/master/.github/workflows/update_api.yml).

**Comment by saimedhi** [comment]
I am working on it
