### ISSUE TITLE
[FEATURE] Add Tests for Notifications Plugin 

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/opensearch-py#636]
### Is your feature request related to a problem?
The [plugins.alerting.AlertingClient.create_destination](https://opensearch-project.github.io/opensearch-py/api-ref/plugins/alerting_plugin.html#opensearchpy.plugins.alerting.AlertingClient.create_destination) API does not work with latest OpenSearch clusters, as destinations have been deprecated in favor of Notification channels. As a result, using that API gives:
```
opensearchpy.exceptions.TransportError: TransportError(405, 'Incorrect HTTP method for uri [/_plugins/_alerting/destinations] and method [POST], allowed: [GET]', 'Incorrect HTTP method for uri [/_plugins/_alerting/destinations] and method [POST], allowed: [GET]')
```

### What solution would you like?
Add support for [Notification APIs](https://opensearch.org/docs/2.11/observing-your-data/notifications/api/), I guess through a different plugin.

### What alternatives have you considered?
One can still use [transport.perform_request](https://opensearch-project.github.io/opensearch-py/api-ref/transport.html#opensearchpy.Transport.perform_request) in order to use Notification channels APIs, but it would be nicer to have it natively supported on the python client.

**Comment by dblock** [comment]
Yes, please contribute! I believe you can add the spec to https://github.com/opensearch-project/opensearch-api-specification and the client will auto-generate the methods.

**Comment by spapadop** [comment]
Thanks the the prompt reply, I raised https://github.com/opensearch-project/opensearch-api-specification/pull/169 just to get this thing going, I'd appreciate your feedback there so that I can continue the work. Many thanks in advance!

**Comment by saimedhi** [comment]
Notifications API Added: Updating Issue to Add Tests for the API. Please feel free to contribute.

**Comment by saimedhi** [comment]
https://github.com/opensearch-project/opensearch-py/pull/668

**Comment by saimedhi** [comment]
resolved
