### ISSUE TITLE
Update Point-in-Time Guide

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#638]
### What is the bug?

The [Point-in-Time guide](https://github.com/opensearch-project/opensearch-py/blob/main/guides/point_in_time.md) includes deprecated API usage without examples of the corresponding new APIs. Please add examples demonstrating the usage of the new APIs as alternatives to the deprecated ones.

Deprecated APIs :       list_all_point_in_time, create_point_in_time, delete_point_in_time
Newly added APIs :     create_pit, delete_pit, delete_all_pits, get_all_pits

**Comment by Djcarrillo6** [comment]
Hi @saimedhi, I'd like to request assignment on this issue!
