### ISSUE TITLE
[BUG] startup time regression traced to elasticsearch

### ISSUE THREAD

**Issue by yoav-orca** [opensearch-project/opensearch-py#67]
**What is the bug?**
I have recently upgraded to `elasticsearch-py` from `7.6.0` to opensearch 1.0 and I have noticed a regression in the startup time of our cli utilities. Apparently, since the introduction of https://github.com/elastic/elasticsearch-py/pull/1180 it will import and initialize pandas and numpy even if they are not used.

**How can one reproduce the bug?**
1. install `pip install git+https://github.com/opensearch-project/opensearch-py.git`
2. run `time python -c 'import elasticsearch'`
3. install `pip install pandas`
4. run `time python -c 'import elasticsearch'`

See increased runtime of 500-800ms.
I would appreciate a switch to turn this thing off if it's not required since it's fairly expensive when not used.

**What is the expected behavior?**
I expect that if the feature is not used then delay the import until the feature is used.

**What is your host/environment?**
N/A

**Do you have any additional context?**
I have reported the same issue to elasticsearch-py, and they have a good fix for the issue - https://github.com/elastic/elasticsearch-py/issues/1715

**Comment by axeoman** [comment]
We just need to cherry-pick that fix and add a proper attribution. `elasticsearch-py` is still under Apache License v2 so it should be fine.

**Comment by Shivamdhar** [comment]
The task can now be closed in the favor of PR: https://github.com/opensearch-project/opensearch-py/pull/107.
