### ISSUE TITLE
[BUG]Fix 'update-api' action

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#670]
### What is the bug?
[update-api](https://github.com/opensearch-project/opensearch-py/blob/main/.github/workflows/update_api.yml) is [failing](https://github.com/opensearch-project/opensearch-py/actions/runs/7791926376/job/21248976558) with below error.
 ```
 remote: error: GH006: Protected branch update failed for refs/heads/automated-api-update.        
  remote: error: Changes must be made through a pull request. Cannot force-push to this branch 
```
### What is the expected behavior?
fix `update-api` action

**Comment by saimedhi** [comment]
@dblock, please take a look

**Comment by dblock** [comment]
I created a new branch protection rule for `automated-api-update` that allows forced pushes and re-ran the job.
https://github.com/opensearch-project/opensearch-py/actions/runs/7791926376/job/21340305981
