### ISSUE TITLE
[BUG] Update the name of the package to be released

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-py#68]
**What is the bug?**
Update the name according to the discussions in ```setup.py``` and other places where necessary

**What is the expected behavior?**
When I release the repository on PyPi, package witht the desired new name should be published.

**Do you have any additional context?**
The current package name is taken and needs to be updated to a new name to publish on PyPi

**Comment by abhinavGupta16** [comment]
@vamshin - This needs to be closed so the MCM can be sent for approval.

**Comment by VijayanB** [comment]
@abhinavGupta16 will send PR out soon. Thanks for bringing this up.
