### ISSUE TITLE
[BUG] 30_max_analyzed_offset failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#686]
### What is the bug?

```
FAILED test_opensearchpy/test_server/test_rest_api_spec.py::test_rest_api_spec[OpenSearch-main/rest-api-spec/src/main/resources/rest-api-spec/test/search/highlight/30_max_analyzed_offset[5]]
```

### How can one reproduce the bug?

Latest builds are failing in this REST spec.

**Comment by saimedhi** [comment]
- The failing test link is [here](https://github.com/opensearch-project/opensearch-py/actions/runs/8246216979/job/22551794860?pr=694).

- This failure is related to [this issue](https://github.com/opensearch-project/OpenSearch/issues/10702).

- The [fix](https://github.com/opensearch-project/OpenSearch/pull/10919) is present in opensearch 2.x, but it is unreleased. Ideally, the fix may be included in version 2.13.0 when it is released.

- **I believe the skip version in this [test](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml#L85) should be set to " - 2.12.99"**. @Xtansia, what do you think? Did I miss anything?



Additional info: 

- I debugged the opensearch-net client to check if this test is executed and noticed that it is skipped for all currently released opensearch versions. It is only running for the [unreleased version](https://github.com/saimedhi/opensearch-net/actions/runs/8261008911/job/22597492465#step:8:28775), where it is working fine. 

- Regarding opensearch-rs, **all** [yaml tests](https://github.com/opensearch-project/opensearch-rs/actions/runs/8261266632/job/22598237813) are skipped for released opensearch versions and are only running for unreleased versions.

**Comment by saimedhi** [comment]
> *  How is the opensearch-net client correctly interpreting the [skip version](https://github.com/saimedhi/opensearch-net/actions/runs/8261008911/job/22597492465#step:8:28766) as " - 2.12.99" even though it is currently specified as " - 2.1.99"

Got it @Xtansia! In opensearch-net's YAML test runner, tests against each opensearch version are taken from the corresponding opensearch version, such as [2.x](https://github.com/opensearch-project/OpenSearch/blob/2.x/rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml#L85) branch when tests are run against 2.x.

On the other hand, opensearch-py uses only yaml tests from the main branch to test all opensearch versions.

Thomas, what do you think is the correct way to test? I'm inclined towards testing all opensearch versions against the opensearch main branch yaml tests. This should be the place where we'll have all the tests correctly, including skip tests that determine whether the test should be run on a particular branch or not.

**Comment by dblock** [comment]
If I understand correctly `OpenSearch/main` and `2.x` are eventually consistent and should be identical? So it shouldn't matter where we take them from. However, I think it's best if we standardized on one way of doing it.

**Comment by dblock** [comment]
Another thought. If OpenSearch 3.x (main) removes an API, would it be deleted from `main`? In that case we want to take tests from `2.x`.

**Comment by saimedhi** [comment]
Listing other failing tests against the unreleased OpenSearch main branch. Working on fixing them.

- FAILED test_opensearchpy/test_server/test_rest_api_spec.py::test_rest_api_spec[OpenSearch-main/rest-api-spec/src/main/resources/rest-api-spec/test/indices/forcemerge/10_basic[2]] 
- FAILED test_opensearchpy/test_server/test_rest_api_spec.py::test_rest_api_spec[OpenSearch-main/rest-api-spec/src/main/resources/rest-api-spec/test/search/highlight/30_max_analyzed_offset[5]] 
- FAILED test_opensearchpy/test_server/test_rest_api_spec.py::test_rest_api_spec[OpenSearch-main/rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries[1]]

**Comment by Xtansia** [comment]
@dblock @saimedhi For both .NET & Rust this behaviour of picking the tests from the matching branch/revision of the OS cluster was inherited in the fork from Elastic. Even if main is eventually consistent, it seems evident that taking the tests intended for a given version will be more reliable.

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/opensearch-py/pull/696.
