### ISSUE TITLE
[BUG]Release drafter workflow failing 

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#705]
### What is the bug?
Release drafter workflow failing when attempted to release opensearch-py 2.5.0

https://github.com/opensearch-project/opensearch-py/actions/runs/8397334839/job/23000462482

**Comment by saimedhi** [comment]
- @zelinh is working on fixing the workflow. This fix needs to be merged into main and backport to branch 2.5
- I deleted  tag v2.5.0. Will create it after getting the fix into 2.5 branch

**Comment by zelinh** [comment]
PR raised for the permission fix. https://github.com/opensearch-project/opensearch-py/pull/706

**Comment by zelinh** [comment]
Manually approval PR is now created.https://github.com/opensearch-project/opensearch-py/issues/708
