### ISSUE TITLE
[BUG]API generator failing

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#710]
### What is the bug?
https://github.com/opensearch-project/opensearch-py/actions/runs/8414867290/job/23039182894#step:5:20

- Newly added [search pipelines](https://github.com/opensearch-project/opensearch-api-specification/pull/172) spec is missing param descriptions. May need to update spec with the param descriptions.

**Comment by saimedhi** [comment]
I haven't debugged yet but will do so when I find the time.

**Comment by saimedhi** [comment]
https://github.com/opensearch-project/opensearch-py/pull/668#issuecomment-2019305007

**Comment by dblock** [comment]
Also https://github.com/opensearch-project/opensearch-py/issues/714

**Comment by saimedhi** [comment]
- Generator failing https://github.com/opensearch-project/opensearch-py/actions/runs/8904988564/job/24455013037

- Will work on fixing it.
