### ISSUE TITLE
[BUG]Resolve All Security Vulnerabilities

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#715]
### What is the bug?

- [ ] https://github.com/opensearch-project/opensearch-py/issues/704
- [ ] https://github.com/opensearch-project/opensearch-py/issues/688
- [ ] https://github.com/opensearch-project/opensearch-py/issues/687
- [ ] https://github.com/opensearch-project/opensearch-py/issues/622
- [ ] https://github.com/opensearch-project/opensearch-py/issues/621

**Comment by saimedhi** [comment]
- All security vulnerabilities can be resolved by upgrading aiohttp to version [3.9.2](https://pypi.org/project/aiohttp/3.9.2/) or higher and black to version [24.3.0](https://pypi.org/project/black/24.3.0/) or later. However, this requires Python version 3.8 or above. Note that opensearch-py currently supports Python versions [3.6 and 3.7](https://github.com/opensearch-project/opensearch-py/blob/main/.github/workflows/test.yml#L10).

- We must either drop support for Python 3.7 and below or find workarounds for all the vulnerabilities.

**Comment by dblock** [comment]
@saimedhi Are 3.6/3.7 EOL? If these are major we should drop support for those.

**Comment by saimedhi** [comment]
> @saimedhi Are 3.6/3.7 EOL? If these are major we should drop support for those.

@dblock, yes [python 3.6, 3.7](https://devguide.python.org/versions/) are EOL
