### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#744]
Coming from https://github.com/opensearch-project/opensearch-clients/issues/64, cleanup unused branches.

For some unused branches we probably want to save state, so maybe note the last revision of any branch being deleted in this issue as it's being closed.

**Comment by saimedhi** [comment]
Please delete branches `bump_version_2.6.0` and `2.x` as development for 2.x versions is now done on the main branch.
@gaya, please assist in deleting these branches. Thank you.

**Comment by gaiksaya** [comment]
Deleted both the branches as stated above. Thanks @saimedhi for 2PR
