### ISSUE TITLE
[BUG] Support Latest OpenSearch versions 2.12, 2.13, 2.14

### ISSUE THREAD

**Issue by davidshq** [opensearch-project/opensearch-py#759]
In the [COMPATIBILITY
](https://github.com/opensearch-project/opensearch-py/blob/main/COMPATIBILITY.md) doc the latest supported OpenSearch version is note as 2.11.1 while the latest released version of OpenSearch is 2.14.0.

I'm curious if this is just a documentation oversight? Or if there is something in particular that needs to be added/changed for 2.12, 2.13, 2.14 compatibility?

**Comment by saimedhi** [comment]
Hello @davidshq, there is an ongoing PR #631 to add OpenSearch 2.12.0 compatibility, so please feel free to contribute. Currently, opensearch-py is compatible with OpenSearch 2.11.1. Thank you.
