### ISSUE TITLE
[BUG] Correct README to reflect published package

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/opensearch-py#78]
**What is the bug?**
The README still has instructions for using git/http for installation.

**How can one reproduce the bug?**
In the README, the install instructions say to use:
`pip install git+https://github.com/opensearch-project/opensearch-py.git` but you can do `pip install opensearch-py`

**What is the expected behavior?**
The readme would be updated to reflect the best practice of using published packages.

**Comment by vchrombie** [comment]
I think this issue is addressed in https://github.com/opensearch-project/opensearch-py/pull/76

**Comment by stockholmux** [comment]
thanks @vchrombie - I missed that!

**Comment by vchrombie** [comment]
Let's leave this issue open, we can close it after the PR #76 is merged.
