### ISSUE TITLE
Ensure DCO Workflow Check

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-py#80]
Coming from https://github.com/opensearch-project/project-meta/issues/17

A Developer Certificate of Origin is required on commits in the OpenSearch-Project.

See [doc.yml](https://github.com/opensearch-project/.github/blob/main/workflow/dco.yml) for an example workflow.  Ensure CONTRIBUTING.md to has a section on the DCO per the [project template](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). 

- [x] DCO Check Workflow
- [x] CONTRIBUTING.md DCO Section

**Comment by vchrombie** [comment]
> A Developer Certificate of Origin is required on commits in the OpenSearch-Project.

Nice :+1: 

Even the [CHAOSS Charter](https://github.com/chaoss/community/blob/master/project-charter.md) requires that contributions are accompanied by a [Developer Certificate of Origin](http://developercertificate.org/) sign-off. For ensuring it, a bot checks all incoming commits.

> See [doc.yml](https://github.com/opensearch-project/.github/blob/main/workflow/dco.yml) for an example workflow. 
> * [ ]  DCO Check Workflow

Just wanted to comment about the other options available. The [dco bot](https://github.com/apps/dco) can be configured at the organization level and it doesn't need any github action workflows.

Example: 
- dco failed -> https://github.com/chaoss/grimoirelab/pull/303
- dco passed -> https://github.com/chaoss/grimoirelab/pull/293

Please feel free to proceed with whatever option the organization maintainers prefer.
Thanks.

**Comment by peternied** [comment]
Initial we tried to using that DCO bot and that request was denied due to its ability to access private repositories.  Instead we built our own check with Jenkins CI for only a handful of repositories, but we never offered and option to smaller repos.  This workflow makes it simple to get all our repos in.

**Comment by vchrombie** [comment]
Okay, thanks for the reply. I think the github actions is the right tool for your usecase. :+1:

**Comment by peternied** [comment]
@vchrombie Can we get the DCO check added on this repo?  This is literally the last one in the campaign

**Comment by vchrombie** [comment]
> @vchrombie Can we get the DCO check added on this repo? This is literally the last one in the campaign

Yes, I don't have any problem with it. Please proceed with whatever suits the requirement.
Thanks.
