### ISSUE TITLE
[BUG] timeout argument in Transport.perform_request is not used

### ISSUE THREAD

**Issue by borisevich-a-v** [opensearch-project/opensearch-py#809]
### What is the bug?
 Timeout argument in Transport.perform_request is not used, because it is redefined just below (see the screenshot).
 

### How can one reproduce the bug?
Try to use `timeout` argument in Transport.perform_request method

### What is the expected behavior?
The argument is used.

### What is your host/environment?
Ubuntu 22.04, python 3.11, OpenSearch 2.14

### Do you have any screenshots?
![image](https://github.com/user-attachments/assets/d5e4b6d6-3285-4e02-8d45-b5163893b22d)

### Do you have any additional context?
PR that solves this bug: https://github.com/opensearch-project/opensearch-py/pull/810

**Comment by dblock** [comment]
Fixed in #810.
