### ISSUE TITLE
[BUG] `timeout` argument gives error for python client.search(.., timeout=400) 

### ISSUE THREAD

**Issue by silkspace** [opensearch-project/opensearch-py#817]
### Describe the bug

`timeout` argument to client.search(.., timeout=400) throws error when specified as either `int` or `float`.  For `timeout=None` it defaults to 10 seconds. 

Error msg: `ConnectionError(Timeout value connect was 400, but it must be an int, float or None.) caused by: ValueError(Timeout value connect was 400, but it must be an int, float or None.)`

we initialize the client like so:

```python
client = OpenSearch(
            self.open_search_url,
            auth=(),
            use_ssl=True,
            verify_certs=True,
        )
```

### Related component

Search:Performance

### To Reproduce

load client and search an index with timeout argument. 

### Expected behavior

Expect to be able to set a float, int (or even string) timeout argument

### Additional Details

**Host/Environment (please complete the following information):**
 - Docker
 - opensearch-py=2.2.0

**Comment by dblock** [comment]
Moved this to opensearch-py. Looks like a bug, appreciate a fix/test @silkspace if you want to give it a shot?

**Comment by dblock** [comment]
Also note https://github.com/opensearch-project/opensearch-py/pull/810 that may have fixed/introduced this, cc: @borisevich-a-v.

**Comment by silkspace** [comment]
I think i will rebuild my docker with the latest version of `opensearch-py` and see if that fixes it, @dblock

**Comment by silkspace** [comment]
Noticing that perhaps @borisevich-a-v's fix hasn't made it into the latest [release](https://github.com/opensearch-project/opensearch-py/releases)?

**Comment by dblock** [comment]
It hasn't been released yet, help make sure it did fix the problem/add tests for the specific example you're using? I can cut a release soon.

**Comment by silkspace** [comment]
I tested docker build using latest OS main:
`pip:
    - git+https://github.com/opensearch-project/opensearch-py.git@main  # contains the timeout fix
`
and the fix apparently *doesn't* address the problem, which is perhaps related to `@query_params` argument mentioned [here](https://github.com/opensearch-project/opensearch-py/issues/816)

**Comment by silkspace** [comment]
I think #816 is closer to the issue.
