### ISSUE TITLE
[BUG] Bug with `AWS` if `id` has special characters

### ISSUE THREAD

**Issue by Danipulok** [opensearch-project/opensearch-py#833]
### What is the bug?
AWS + special characters in 'id' result in:
```
opensearchpy.exceptions.AuthorizationException: AuthorizationException(403, '{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n\'GET\\n/index-name/_doc/cool_bot%21-f9aa36ea-b8a5-4890-957e-29f000beec86%40localhost\\n\\nhost:search.us-west-2.es.amazonaws.com\\nx-amz-date:20241017T115545Z\\n\\nhost;x-amz-date\\ne3b0c4429\'\\n\\nThe String-to-Sign should have been\\n\'AWS4-HMAC-SHA256\\n20241017T115545Z\\n20241017/us-west-2/es/aws4_request\\n262223abc008b0d31e74a714950\'\\n"}')
```

### How can one reproduce the bug?
```python
import boto3
from opensearchpy import AWSV4SignerAsyncAuth, AsyncHttpConnection, AsyncOpenSearch

OPENSEARCH_URL = "https://search.us-west-2.es.amazonaws.com"
OPENSEARCH_AWS_ACCESS_KEY_ID = "..."
OPENSEARCH_AWS_SECRET_ACCESS_KEY = "..."
OPENSEARCH_AWS_REGION = "us-west-2"

kwargs = {}
credentials = boto3.Session(
    aws_access_key_id=OPENSEARCH_AWS_ACCESS_KEY_ID,
    aws_secret_access_key=OPENSEARCH_AWS_SECRET_ACCESS_KEY,
).get_credentials()
auth = AWSV4SignerAsyncAuth(credentials, OPENSEARCH_AWS_REGION)
kwargs["http_auth"] = auth
kwargs["connection_class"] = AsyncHttpConnection


async def main() -> None:
    opensearch_client = AsyncOpenSearch(
        OPENSEARCH_URL,
        **kwargs,
    )

    REAL_ID = "cool_bot@localhost"
    await opensearch_client.get(index="index_name", id=REAL_ID)

    await opensearch_client.close()


if __name__ == "__main__":
    asyncio.run(main())
```

### What is the expected behavior?
When using localhost openseach run via docker everything's okay. So I guess there's a problem with `AWSV4SignerAsyncAuth` somewhere

### What is your host/environment?
Win10
Python 3.12.3
opensearch-py==2.7.0
boto3==1.35.2

### Do you have any additional context?
Maybe it's a bug in `boto3.Session` ? If yes, please tell me, I will open the issue there.
And I consider this as an issue at all since with non-aws and localhost everything's okay.
With all other ID like "foo" everything's okay with the same code, so it's not a credentials problem

**Comment by dblock** [comment]
Start by checking that your setup/credentials are actually correct?

1. Try `curl` or `awscurl` and make sure that works, some examples in https://code.dblock.org/2022/07/11/making-sigv4-authenticated-requests-to-managed-opensearch.html. 
2. Try a known working Python demo in https://github.com/dblock/opensearch-python-client-demo.   
3. Let's see what the difference between your code and (2) is.

**Comment by fabiopedrosa** [comment]
I'm seeing the same bug happen, only when using the `AsyncHttpConnection`

**Comment by Danipulok** [comment]
@fabiopedrosa thanks a lot for the comment, could not find a time for the asked code. So when "AsyncHttpConnection" is not used everything's good?

**Comment by fabiopedrosa** [comment]
I narrowed down the bug to this line in `helpers\asyncsigner.py`:

```
from urllib.parse import unquote
aws_request = AWSRequest(
    method=method,
    url=unquote(url),
    data=body,
)
```

**Comment by fabiopedrosa** [comment]
I've created a PR for this issue to be fixed: https://github.com/opensearch-project/opensearch-py/issues/833

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta)]

**Comment by dblock** [comment]
@nathaliellenaa want to take this?

**Comment by nathaliellenaa** [comment]
Sure, I can take this one!

**Comment by dblock** [comment]
I merged a fix for this in https://github.com/opensearch-project/opensearch-py/pull/848, thanks @nathaliellenaa.

**Comment by dblock** [comment]
@Danipulok @fabiopedrosa if you have a moment, give that fix a try?
