### ISSUE TITLE
[FEATURE] Consistent connection pooling setting

### ISSUE THREAD

**Issue by samypr100** [opensearch-project/opensearch-py#844]
### Is your feature request related to a problem?

When using `OpenSearch` client, setting `pool_maxsize` allows you to increase the connection pool size as shown in the [documentation guides](https://github.com/opensearch-project/opensearch-py/blob/main/guides/connection_classes.md#connection-pooling).

The same is not true when using `AsyncOpenSearch` and it seems `pool_maxsize` does not have the desired effect.

The argument has to be named `maxsize` for it to work and take effect as shown in https://github.com/opensearch-project/opensearch-py/blob/d54aab4eda2d979572b628be9284addf99eccec0/opensearchpy/connection/http_async.py#L49

### What solution would you like?

I would like `pool_maxsize` to work for `AsyncOpenSearch`, e.g. by also setting `maxsize` internally.

### What alternatives have you considered?

Right now, I instantiate OpenSearch/AsyncOpenSearch clients with both `pool_maxsize` and `maxsize` set to ensure consistent settings, but its undesired from a DevEx perspective to have to use one or the other when moving between sync and async.

### Do you have any additional context?

Debugger can show `self._limit` set to `10` (the default) if `pool_maxsize` is set when creating a new instance of `AsyncOpenSearch`. The value can be changed only if `maxsize` is passed instead to `AsyncOpenSearch`.

https://github.com/opensearch-project/opensearch-py/blob/d54aab4eda2d979572b628be9284addf99eccec0/opensearchpy/connection/http_async.py#L284-L286

**Comment by dblock** [comment]
Thanks for reporting this, please do contribute a fix. Generally I'd want a lot of the setup code to be refactored so that we don't have differences between sync/async for anything that can be set in both.
