### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by merlinz01** [opensearch-project/opensearch-py#846]
Last release was 2.7.2 on August 22.

**Comment by merlinz01** [comment]
Ping.

**Comment by dblock** [comment]
I got those things merged, but it's already late here in NYC and Thanksgiving in the US tomorrow and Friday, so I'd rather not release something and find it broken those days and have to scramble to fix. Will do first thing Monday. In the meantime, appreciate if folks could test https://github.com/opensearch-project/opensearch-py/pull/848 from HEAD.

**Comment by dblock** [comment]
I released 2.8.0, https://github.com/opensearch-project/opensearch-py/releases/tag/v2.8.0

**Comment by dblock** [comment]
@saimedhi Releasing is thoroughly documented in https://github.com/opensearch-project/opensearch-py/blob/main/RELEASING.md.
