### ISSUE TITLE
Bulk documentation

### ISSUE THREAD

**Issue by marl2en** [opensearch-project/opensearch-py#86]
opensearch_py works just fine. Thank you !!!
Trying to use it with suricata. 
To index documents one by one as described in the short documentation works, but how to index like 100 documents per second? 

A bulk function is implemented in opensearch_py, but couldn't figure out how to use it. client.bulk( some arguments) ?

**Comment by axeoman** [comment]
Using `opensearchpy.helpers.bulk` is much more convenient:
```python
from datetime import datetime

from opensearchpy import OpenSearch
from opensearchpy.helpers import bulk

host = 'localhost''
port = 9200
auth = ('admin', 'admin'')

client = OpenSearch(
    hosts = [{'host': host, 'port': port}],
    http_compress = True,
    http_auth = auth,
    use_ssl = True,
)

index_name = 'python-test-index3'

actions = [
  {
    "_index": "python-test-index3",
    "_type": "tickets",
    "_id": count,
    "_source": {
        "any":"data" + str(count),
        "timestamp": datetime.now()}
  }
  for count in range(0, 10)
]

bulk(
    client,
    actions,
)

response = client.search(index=index_name)
print('\nSearch results:')
print(response)
```

**Comment by axeoman** [comment]
I believe the question is being answered. Please, reopen the issue if it still needs some clarification.
