### ISSUE TITLE
[FEATURE]Does opensearch-py 2.8.0 support OpenSearch 2.14.0?

### ISSUE THREAD

**Issue by J-WChan** [opensearch-project/opensearch-py#868]
Hello,
Please note that I used a translation tool to write this message, so I apologize for any language errors.I hope this message finds you well.

I am currently using opensearch-py 2.8.0 and would like to know if it is compatible with OpenSearch 2.14.0. Are there any known issues or limitations when using this combination?

Are there any plans or timelines to ensure compatibility with OpenSearch 2.14.0? If this combination is already supported, could you kindly confirm?

Thank you for considering this request and for all the amazing work you do for this project!

Best regards,

**Comment by dblock** [comment]
Yes, this is supported, see https://github.com/opensearch-project/opensearch-py/blob/main/COMPATIBILITY.md. There aren't any known compatibility issues.
