### ISSUE TITLE
api

### ISSUE THREAD

**Issue by linruoma** [opensearch-project/opensearch-py#87]
I know opensearch has an incomplete Python API.  One question is: Can we use the python API of elasticsearch on opensearch

**Comment by VijayanB** [comment]
@linruoma Sorry for updating this issue late. We released python dsl ( high level python client for OpenSearch ) https://pypi.org/project/opensearch-dsl/ . Please try this in your project and open issues at [dsl-py](https://github.com/opensearch-project/opensearch-py/issues) if you find any issues. Thanks.
