### ISSUE TITLE
[BUG] Non-200 responses are parsed as json even when the data isn't json.

### ISSUE THREAD

**Issue by mccullocht** [opensearch-project/opensearch-py#92]
**What is the bug?**

HTTP `Connection` implementations will take non-200 responses and parse the data as json to help produce more complete exceptions. They do this even if the response contains data of a different type (like text/plain), triggering log messages.

**How can one reproduce the bug?**

```
curl -k -u"admin:wrong" -w"\n%{http_code}\n%{content_type}\n" https://localhost:9200/_cluster/health
Unauthorized
401
text/plain; charset=UTF-8
```

This condition can also be reproduced in tests for the connection classes that ship with this library.

In our production environment we see this most often when rotating passwords for our client roles: the password changes, a routine operation receives a 401 which we catch as an AuthorizationException, but the library also logs that it could not parse the (plain text) response.

**What is the expected behavior?**

Do not attempt to parse the response as json when it is not json. This will also cause us to stop logging when parsing fails.

**What is your host/environment?**
Docker image opensearchproject/opensearch:1.1.0 + security plugin
opensearch-py==1.0.0
Python 3.9.5

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
I put up a small [PR](https://github.com/opensearch-project/opensearch-py/pull/91) to fix this.

**Comment by axeoman** [comment]
Thanks again for the contribution :+1:

**Comment by mccullocht** [comment]
Thanks for the review!
