### ISSUE TITLE
[BUG] Client uses POST for read operations, preventing read only permissions

### ISSUE THREAD

**Issue by SamStephens** [opensearch-project/opensearch-py#95]
**What is the bug?**

The client uses [POST for read operations such as Search](https://github.com/opensearch-project/opensearch-py/blob/ef0c23c0e4fb089e147d868a9ebb1e0feae2b770/opensearchpy/client/__init__.py#L1593-L1599). This is problematic when it comes to managing permissions, especially in AWS where the HTTP verbs are the operations you can control access to.

For example, [the CDK grantRead method grants HEAD and GET](https://github.com/aws/aws-cdk/blob/e6c4ca5e71934e890eabe41190e9c2d0bd42aefb/packages/%40aws-cdk/aws-opensearchservice/lib/perms.ts#L1-L4). So you [grant read access to a domain, and then see some read operations fail](https://github.com/aws/aws-cdk/issues/17761).

**How can one reproduce the bug?**

Setup an Opensearch domain. Grant a principal HEAD and GET permissions. Have that principal attempt a search via the python client. See the permission denied message because it uses a POST.

**What is the expected behavior?**

I'd expect that even if the Opensearch API allows for violation of HTTP semantics by allowing both GET and POST for the search operation, the client libraries should respect those verbs, and use GET rather than POST for read operations that allow both.

Without this, I cannot grant a Python client search permission without granting them POST and allowing them write access via operations such as [update](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html).

**Comment by wbeckler** [comment]
Given that the protocol of the search service requires POST for some reads, the issue does lie here: https://github.com/aws/aws-cdk/issues/17761

I propose we close this issue if there aren't any objections.

**Comment by SamStephens** [comment]
> Given that the protocol of the search service requires POST for some reads, the issue does lie here: [aws/aws-cdk#17761](https://github.com/aws/aws-cdk/issues/17761)
> 
> I propose we close this issue if there aren't any objections.

Yeah, now I understand the situation better, I concur.

**Comment by dblock** [comment]
Took me a while to grok this. The reason why some reads require a POST is well explained in https://github.com/aws/aws-cdk/issues/17761#issuecomment-1186674964 (thank you). Now that itself is potentially a problem, maybe it's worth raising a meta issue in OpenSearch core so that all reads can be done with GETs?

I agree that we can close the issue here.

**Comment by SamStephens** [comment]
> Took me a while to grok this. The reason why some reads require a POST is well explained in [aws/aws-cdk#17761 (comment)](https://github.com/aws/aws-cdk/issues/17761#issuecomment-1186674964) (thank you). Now that itself is potentially a problem, maybe it's worth raising a meta issue in OpenSearch core so that all reads can be done with GETs?
> 
> I agree that we can close the issue here.

@dblock I'll leave it to your judgment as to whether to raise a an issue on OpenSearch core. Please post the issue here if you do; I'd be curious to observe the disucssion.

My take is that the use of POST for an operation like scroll is semantically correct, as you are setting state.

To my mind, the best thing Opensearch core can do is make it crystal clear in the documentation that trying to control read/write access by HTTP verb misunderstands the Opensearch API, and possibly to put the weight of the core team behind issues such as https://github.com/aws/aws-cdk/issues/17761 against projects that are operating under this misunderstanding.

**Comment by dblock** [comment]
I think it's always worth having a discussion @SamStephens, even if for posterity so we don't "rediscover" the same problem/solution/conversation! I opened https://github.com/opensearch-project/OpenSearch/issues/4177

**Comment by dblock** [comment]
For documentation I opened https://github.com/opensearch-project/documentation-website/issues/863
