### ISSUE TITLE
[BUG] AysyncOpenSearch doesn't import

### ISSUE THREAD

**Issue by andrew-matteson** [opensearch-project/opensearch-py#96]
**What is the bug?**
Maybe a documentation issue regarding `async`, not sure.

I have:
```
from opensearchpy import RequestsHttpConnection, AsyncOpenSearch
```
in my code, which errors with:

ImportError: cannot import name 'AsyncOpenSearch' from 'opensearchpy'

**What is the expected behavior?**
Import of async client succeeds.

**What is your host/environment?**
 - OS: mac
 - Version 1.0.0

**Comment by VijayanB** [comment]
@andrew-matteson Did you try like below?
```
pip3 install opensearch-py[async]
```

![Screen Shot 2021-12-01 at 4 51 38 PM](https://user-images.githubusercontent.com/11067894/144337833-f36c4299-3327-44b6-adc3-12386a1b90e8.png)

**Comment by andrew-matteson** [comment]
I missed the hyphen in the pip install. Thanks!
