### ISSUE TITLE
[BUG] CI fails for main

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-py#97]
**What is the bug?**
CI fails for integration test ( opensearch, true )

**How can one reproduce the bug?**
https://github.com/opensearch-project/opensearch-py/runs/4186359419?check_suite_focus=true

**What is the expected behavior?**
CI should pass

**What is your host/environment?**
Github

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
We should not run against latest since it is a moving target. We should run against released tested version and increment only after we verify it works with this library.

**Comment by axeoman** [comment]
Looks like this is the reason, but I like the idea to stop running the latest OpenSearch in test runs.
```
[2021-12-13T19:48:23,098][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [c2d66e4acba0] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
 ```

**Comment by axeoman** [comment]
Closing for now, since it has been fixed.
Perhaps we should create our own certificates or somehow generate demo "kirk" certificates for OpenSearch so we can run integration tests with versions >1.0.0
